### ISSUE TITLE
Alexa App not working on Arduino core 2.4.0

### ISSUE THREAD

**Issue by wcbuerste** [Aircoookie/WLED#10]
Hi,
I can succesfully use the webinterface to controll an LED strip and it is found in the Alexa app without any issues. The on/off status and brightness changes in the webinterface also gets updated in the Alexa App. But performing actions like switching off or adjusting the brigness from the app side, doesn´t have any effect.
Am I missing something?
Thank you, David

**Comment by Aircoookie** [comment]
Hey,
I believe this is an issue I already know that happens when you use the ESP8266 core version 2.4.0 and compile the source yourself. There is a bug in the Alexa protocol which the ESP can't handle properly in that Arduino core version.
The "fix" for now is to either use Arduino core 2.3.0 or to apply this workaround: https://github.com/Aircoookie/Espalexa/issues/6#issuecomment-366533897
Let me know if this solves the problem for you!

**Comment by wcbuerste** [comment]
Thank you,
must have missed this. Works perfect now! =)
Anyway, what would be the benefit of getting a Hue Hub and use the integration? May I use is for color changes on voice commands than?

**Comment by nbietz** [comment]
Would it be possible to add each saved preset as a new "device" discoverable by Alexa. Then it could be possible to use Alexa voice control to switch between saved patterns/presets.

**Comment by Aircoookie** [comment]
Yes, this is a great idea! I'll add it soon, but it will take a while as there is a lot to do currently! I might even extend that so you could set the color by saying "Alexa, set <Device> hue to 20 percent", where you just roughly need to know, which hue on the 0-100 scale your color is.

**Comment by Aircoookie** [comment]
@Jakespta thanks for the feedback! I've never tried this workaround with core 2.4.1, just 2.4.0. Did a quick look and in 2.4.1 the line to replace is 192, not 193, but I believe you already figured that out!

Have you tried this with WLED or with Espalexa?

I'll have to install 2.4.1 and see if I can find a new workaround if the 2.4.0 workaround doesn't work anymore.
