### ISSUE TITLE
Some palettes contain (very) wrong colors

### ISSUE THREAD

**Issue by DoubleStrike** [Aircoookie/WLED#1013]
**Describe the bug**
As a new user I was testing several palettes and found that some contain colors that don't make sense.  For example the ES Vintage 57 GP palette contains a vivid red.

**To Reproduce**
Look at the palette definition in palettes.h
`const byte es_vintage_57_gp[] PROGMEM = {
    0,   2,  1,  1,
   53,  18,  1,  0,
  104,  69, 29,  1,
  153, 167,135, 10,
  255,  46, 56,  4
};`

The final color (255,  46, 56) is a bright red and the second to last (153, 167,135) is a bright greenish-cream.  If you look at the original palette (http://soliton.vm.bytemark.co.uk/pub/cpt-city/es/vintage/tn/es_vintage_57.png.index.html) those colors are quite wrong.  A few other palettes display similar issues.

**Expected behavior**
The palette should contain cohesive colors that go together based on the source palette.

**WLED version**
 - 0.10.0

I am more than happy to jump in and try cleaning some of these up if someone can suggest the best way to do so.

**Comment by Aircoookie** [comment]
Hi and thank you for the report!
I just took a look. The palettes included in WLED are gamma corrected, so the individual colors are more dim than in the original, but the hues match. The WLED palettes neither contain the bright red nor greenish cream, since the first of every four values is the mapping index of the RGB color on the palette. Like this:
```cpp
//I  R  G  B   I   R  G  B    I   R   G  B    I    R   G   B    I   R   G  B
{ 0, 2, 1, 1, 53, 18, 1, 0, 104, 69, 29, 1, 153, 167,135, 10, 255, 46, 56, 4 };
```
It could still be that the palette has been gamma corrected to aggressively. I just took the palettes from a FastLED example, so the gamma correction was already applied this way. We could try experimenting with the values a bit to make the palettes visually match the ones on cpt-city a bit better!
