### ISSUE TITLE
Philips Hue Sync

### ISSUE THREAD

**Issue by renanbarbalho** [Aircoookie/WLED#1021]
hello,
I configure my wled with ip of my hue brigde and i received this error:

![image](https://user-images.githubusercontent.com/3430717/86306547-efe93180-bbea-11ea-95bd-164ef70b51f9.png)

how to solved?

**Comment by Aircoookie** [comment]
Hi! It says that the light with ID `10` you are trying to sync to does not exist.
Please go to the About section of the Hue app and confirm that the light with the number 10 exists and is the one you want to sync to! If the light actually exists, I need to look into it because it might be bug.
Thank you!

**Comment by renanbarbalho** [comment]
Thanks for your answer. Where I find the IDS? Because I have four lamps (sala 1, sala 2, game 1 and game 2) My first tried was set ID 1 with same error.
Do you have any idea?

**Comment by toto79** [comment]
@renanbarbalho: there are different opportunities. Most of the time i use WinHue to explore my hue bridge. Under view -> bulbs view you'll see the Light IDs. It's also possible to do it with the hue api. ...

**Comment by renanbarbalho** [comment]
@toto79 thanks for your help, this app was killer! I found the bulbs ID and now myLed was connected with my bridge.

Thanks a lot!
