### ISSUE TITLE
Improved Alexa  support

### ISSUE THREAD

**Issue by halfajobj** [Aircoookie/WLED#1054]
Hi there I have recently moved from google to alexa, i can control my wled device via alexa however i cant change the effect via voice ie rainbow etc. Could a wled skill be created for this or implemented in next version

**Comment by Aircoookie** [comment]
Hi,
since WLED uses an emulation of the local Philips Hue api (which does not have a concept of effects), this is unfortunately not directly possible.
It would be possible to develop a skill for WLED with this functionality, but I neither have the resources or cloud infrastructure to implement it. Maybe someone else does though :)

**Comment by siggel** [comment]
might solve this: https://github.com/Aircoookie/WLED/pull/2787
