### ISSUE TITLE
error: ambiguous overload for 'operator~' (operand type is 'IPAddress')

### ISSUE THREAD

**Issue by raymiec** [Aircoookie/WLED#106]
/wled07_notify.ino: In function 'void notify(byte, bool)':
wled07_notify:48:17: error: ambiguous overload for 'operator~' (operand type is 'IPAddress')
   broadcastIp = ~WiFi.subnetMask() | WiFi.gatewayIP();
                 ^

I'm on a different mac installed everything fresh, maybe libraries or something messed up,  any ideas on this one?

i can change it to  broadcastIp = WiFi.gatewayIP();   and will compile not sure of the implications of that.

Thanks.

**Comment by Aircoookie** [comment]
Thanks for the report! I've found out that this only happens with the latest 2.5.0 ESP8266 Arduino core, versions before that work fine. This is because IPv6 is now internally supported by ESP8266 and it can't make sure that it's an IPv4 address for this operation.

Your change breaks the UDP notifier, so ESPs where it is installed can no longer send sync packets to other WLED ESPs. The fix is:
`broadcastIp = ~uint32_t(WiFi.subnetMask()) | uint32_t(WiFi.gatewayIP());`

I will push it to the master branch shortly!

**Comment by vietbac1973** [comment]
Thanks.
