### ISSUE TITLE
Hideously Geeky... 

### ISSUE THREAD

**Issue by timmills** [Aircoookie/WLED#1222]
I've got a rack at home with a bunch of server and network equipment.

I'd like - (because we all like flashing lights) to stick the LED strips to the rack glass in front of each server and display activity of the device, HD capacity, network activity, CPU usage etc..

I'm thinking MQTT? has anyone else tried something like this? essentially turning a range/segment of LEDs into gauges

**Comment by Aircoookie** [comment]
Hi, that is a very cool idea!
To get gauges to work well, I would recommend using the `Percentage` effect, whose intensity (when set between 0-100) will illuminate that percentage of the segment.
MQTT is not (yet) ideal for it, because it doesn't support the JSON API yet, which is the recommended way to manipulate segments (you'll want one segment per gauge)
Let us know how it goes :)

**Comment by huggy-d1** [comment]
If you have something that can trigger MQTT messages, can it also trigger a CURL command - and use the JSON API?
I use CURL to access the Govee API which requires sending JSON.  Same thing would work for WLED segment control.
