### ISSUE TITLE
LED Strip suddenly stopped to working

### ISSUE THREAD

**Issue by danieely01** [Aircoookie/WLED#1235]
Hello, My LED Strip suddenly stopped to working. 
(I ordered all of these parts: https://tynick.com/blog/11-03-2019/getting-started-with-wled-on-esp8266)
Yesterday when I firstly flashed my ESP8266 it was perfect. I connected to the WI-Fi, It worked with the WLED Application too, the LED Strip's lights worked.( WS2812B LED Strip)  it was fine. Untill today. When I connect my ESP8266 to my LED Strip (WS2812B LED Strip) with jump wires, I see nothing. No lights at all. I plugged the wires to the right places (Power - Vin, Ground - GND and Digital out to the D4.)
I hope my LED strip haven't died after 1 day.

Thank you for your help!

**Comment by huggy-d1** [comment]
Do you have a picture of the wiring of the strip to the LED strip?
Curious why it was not still wired up today?  Bad cat?
Does the WLED AP show up as a WiFi network?  Does the dev board LED light up when you apply power?

**Comment by danieely01** [comment]
![4](https://user-images.githubusercontent.com/72511240/95363485-d2092800-08cf-11eb-92fe-7459d9604070.jpg)
![3](https://user-images.githubusercontent.com/72511240/95363489-d33a5500-08cf-11eb-90d3-4a84e38945b3.jpg)
![2](https://user-images.githubusercontent.com/72511240/95363494-d3d2eb80-08cf-11eb-8eda-000b7410e4bc.jpg)
![1](https://user-images.githubusercontent.com/72511240/95363498-d46b8200-08cf-11eb-818f-c63538720758.jpg)

Yeah, the WLED AP show up as a WiFi network, and It says It's connected and online. On the dev board everything is okay.

**Comment by huggy-d1** [comment]
Thanks for the pictures.  Tracing wires I have a bit of confusion.

What happens between the NodeMCU Dupont jumpers and the JST connector?  The NodeMCU does not have enough power to directly power an LED strip.

Is WLED loaded with firmware to send out the data pin set to GPIO2 (D4)?  I ask because it might be possible that jumper is on the wrong NodeMCU pin.  It might be GPIO4 (D2)?

Also, having the strip rolled up like that localizes heat and can burn up the strip.  Limit current to around 25-30% and avoid color "white" and effects that turn all LEDs on at the same time.  When it's unrolled, these limits are not necessary to protect the strip.

If there is an external LED strip power supply, be very careful not to burn up a computer's USB port and _always_ keep the NodeMCU disconnected.

If the NodeMCU was powering the LED strip directly yesterday, it probably cannot do it today (or ever again).

**Comment by danieely01** [comment]
Thank for your reply.
I'm not really into this yet, so I have some misunderstanding, I'm really sorry about that.
So, for the first question: I use jump wires to connect them, like this: 
![cnt](https://user-images.githubusercontent.com/72511240/95370919-c91d5400-08d9-11eb-9622-57bf60ab47ed.jpg)
![cnt2](https://user-images.githubusercontent.com/72511240/95370994-e3efc880-08d9-11eb-882f-a8db88164aeb.jpg)

For the second question: I downloaded the latest firmware, and flashed to the Dev board.The jumper wire connected to the D4 pin: 
![d4](https://user-images.githubusercontent.com/72511240/95371602-b5262200-08da-11eb-8b12-63660c2f3e62.jpg)
I don't have any power supply, because the guide didn't mention that. Thank you for the tips!!
What power supply should I buy for these?
