### ISSUE TITLE
Default Settings beim booten werden nicht gespeichert.

### ISSUE THREAD

**Issue by Tihass1975** [Aircoookie/WLED#1289]
Hallo an das WLED Team,

wenn man unter **led References** -> **Defaults** -> **Apply Preset at boot** zum Beispiel auf Slot 1 setzt, werden Einstellungen wie  **Default brightness** und **Turn LEDs on after power up/reset** ignoriert. Wenn man **Apply preset 0 at boot** belässt, werden die Einstellungen berücksichtigt.

Ich benutze WLED 0.10.2 in Verbindung mit einem WEMOS D1 mini Pro und APA102 LED Stripes.

Gruß
Matthias

**Comment by csantelman** [comment]
English translation - 
If you set, for example, slot 1 under led References -> Defaults -> Apply Preset at boot, settings such as default brightness and turn LEDs on after power up / reset are ignored. If you leave Apply preset 0 at boot, the settings are taken into account.

**Comment by Aircoookie** [comment]
Hi! In v0.11.0 habe ich dieses Verhalten geändert, die beiden Einstellungen sollten nun auch bei gesetztem Boot preset funktionieren :)

Hi! I have changed this behavior in v0.11.0, the two settings will now function correctly with boot preset enabled

**Comment by csantelman** [comment]
I'm confused - I still can't get this to work.  In my case, I want to use a wifi enabled switch to control the power supply, which would then control the lights.

- Using the wled app on my phone - I set the lights to be a non-default color - blue.
- Navigate to config/LED Preferences, check the "Set Current preset cycle setting as boot default" box
- Save (Settings saved message appears)
- Power off the lights via the phone app, power back on, and the light is blue.  This is expected behavior.
- Turn off the wifi switch, lights go off (expected)
- Turn on the wifi switch, lights come on, but are back to the defualt color (unexpected)

**Comment by Aircoookie** [comment]
@csantelman please don't comment the same in multiple issues. Replied to you in #1414 :)

**Comment by csantelman** [comment]
@Aircoookie  - sorry...

**Comment by Aircoookie** [comment]
no worries :)

**Comment by tourer4778** [comment]
Hello,
Is it also possible that the LEDs are off, after power on (relay too) ?
