### ISSUE TITLE
Green and Blue mixed up with ws2801

### ISSUE THREAD

**Issue by tilmanschwaner** [Aircoookie/WLED#1318]
Green and Blue is mixed up in WS2801-Image

**Comment by cschuhknecht** [comment]
I don't know what the "-Image" means, but if the strip shows wrong colors because green and blue are swapped, you can change the color order in the LED settings just above "Defaults".

**Comment by huggy-d1** [comment]
Since there is not exact specification what the color order should be, so LED strip manufacturers choose what suits their capabilities or perhaps their notion of what the correct order should be.

I prefer RGB, but can see reasoning for BGR (English, alphabetical), or any other order for a different language's preferred ordering.

WLED lets you match pixel color order to the LED strip connected to it.  I suspect the bug is not with WLED, but with the Issue poster not realizing this capability existed.

**Comment by jezmck** [comment]
@tilmanschwaner, can you please confirm that you're able to use the **Color order** setting in **Config > LED Preferences**?

![image](https://user-images.githubusercontent.com/89996/98523534-f0b36380-226d-11eb-9f13-31563329a845.png)

If so, please mark this issue as closed.

**Comment by tilmanschwaner** [comment]
I haven´t seen this option, it works now, thank you!
