### ISSUE TITLE
Brightness factor is ignored after E1.31 data is finished

### ISSUE THREAD

**Issue by twlare** [Aircoookie/WLED#1363]
**Describe the bug**
Brightness factor is ignored after an xLights E1.31 effect is finished and control returns to the WLED effect that was running before the xLights data was processed.

**To Reproduce**
In LED Preferences, set Default brightness to 255 and Brightness factor to 10%. Save changes. WLED effects use 10% brightness. Send E1.31 data from xLights. xLights effects use 10% brightness. When the xLights effect ends, WLED will display the previous WLED effect at 100% brightness.

**Expected behavior**
WLED effects should always use the Brightness factor.

**WLED version**
 - Board: Wemos D1
 - Version 0.11.0p
 - Format Self-compiled, changed only platformio.ini - "default_envs = d1_mini"

**Additional context**
It is desirable to use Brightness factor to control LED brightness from programs like xLights. Without a global brightness limiter, each effect in xLights would need to have its brightness adjusted. If you want to raise or lower the brightness of an LED string, instead of changing a single brightness factor, each effect would need to be modified. Other LED controllers such as ESPixelStick have a similar global brightness limiter.

**Comment by twlare** [comment]
I also notice that in the LED Preferences page, Brightness factor has an allowable range of 1 to 255 percent. Should it be 1 to 100?

**Comment by Aircoookie** [comment]
Thank you, that was an oversight. Fix coming shortly!

1 to 100 will be the most commonly used range, but a factor >100% is supported and can be useful, for example if you sync your lights and run them at half brightness most of the time. If you then have one light that appears dimmer because it has a diffuser, you can run it a bit brighter to compensate. Of course, it is capped at 255 :)
