### ISSUE TITLE
Preset delete confirmation

### ISSUE THREAD

**Issue by ToXIc-Dev** [Aircoookie/WLED#1404]
**Is your feature request related to a problem? Please describe.**
Accidental deletion of presets

**Describe the solution you'd like**
A confirmation prompt

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thank you for your ideas for making WLED better!

**Comment by Aircoookie** [comment]
Thank you for the suggestion!
I thought about adding a confirmation as well, but did not because I think it would make mass-deleting (cleanup) of old presets a lot more annoying.
In day-to-day use, you also still need to click the little down-facing arrow to expand the preset options before you can delete it, so accidental deletion could only happen if you are currently editing a preset.
I could add an optional confirmation though if accidental deletion turns out to indeed an issue.

**Comment by ToXIc-Dev** [comment]
@Aircoookie You make some good points, maybe it's not that big of an issue.
I just thought it could be a possible issue but now I think about it, it's probably fine.

**Comment by huggy-d1** [comment]
How about an "undo" delete option - only available as the next command after a deletion.  After anything else, the Undo Delete option goes away.

**Comment by Aircoookie** [comment]
@huggy-d1 good idea! We can simply temporarily save the deleted preset and restore it with a single click

**Comment by blazoncek** [comment]
Preset delete confirmation is implemented. For "undo" please open new issue.
