### ISSUE TITLE
Question: Multiple lights with Hue syncing

### ISSUE THREAD

**Issue by jabach18** [Aircoookie/WLED#1436]
Hey there, 
so little question, when I have multiple ESPs running WLED and syncing all to the same Hue light, they each send a request to the Hue bridge am I right? So if I have more WLEDs running the hue bridge will eventually get slower with each added wled light?

Because if this is true I will probably build a litte "hub" myself which sends one request to a hue bridge and then syncs all wleds ESPs over the http api, this would be much more efficient for the hue bridge if I understand this correctly.

Thanks in advance!

**Comment by Aircoookie** [comment]
Hi!
Sorry, I must have missed your issue :( I hope this is still relevant for you or someone else in the future :)
Yes, if you enable Hue sync on each WLED light and pair it to the bridge, each light will poll the bridge separately, which is not good for the bridge and your wireless network performance.

Instead I would recommend setting up only a single ESP (preferably with good signal strength and low amount of LEDs) and setting up the WLED UDP sync functionality between all lights you want to sync up to that hue light. I am personally using that config successfully since 2 years :)
