### ISSUE TITLE
WLED: device unreachable

### ISSUE THREAD

**Issue by jsypien3** [Aircoookie/WLED#1505]
I keep having issues with using the wled app. I’m running the latest app version and wled 11.0. I keep occasionally getting the node mcu to be controllable from the app but otherwise I need to control my nodes separately using the Ap. Can I fix this issue? Also how can I control multiple node mcu’s to have them preform the same effect at the same time. 
Many thanks

**Comment by huggy-d1** [comment]
First, you need to get them all on the same WiFi network.  You cannot sync them up otherwise.

Once you get them all on the same wifi network, look at the "SYNC" button on the WLED menu.  Decide which device is your "master", perhaps even name it "WLED-Master" to make it easier.  Have that one SEND updates.  All the others, have them RECEIVE updates.  Be careful not to enable both send and receive updates.  That causes a time-paradox and you'll be time-warped back to the future. :)
