### ISSUE TITLE
Is it a slot or is it a preset or is it a favorite?

### ISSUE THREAD

**Issue by bbrendon** [Aircoookie/WLED#1571]
It seems WLED docs/code uses these words interchangeably when it's all the same thing? If so can one be chosen?

**Comment by Aircoookie** [comment]
Slot - old name for a preset - no longer in use since 0.11
Preset - the proper name for a persistantly saved set of segments, each set to a specific color and effects
Favorites - The name of the UI tab presets are set in. In the future, this will include more stuff than just presets - e.g. sequences saved on an SD card, or playlists :)
