### ISSUE TITLE
Play a File from File System 

### ISSUE THREAD

**Issue by NormBot1008** [Aircoookie/WLED#1684]
Hi, I have a question,

can I play a tpm2 file in WLED on the file system?

**Comment by JvPeek** [comment]
Short and simple answer: no, you can't

Extensive answer (which is why this is 23 days later): You could add a TPM2 parser as a usermod. This would require a bit of coding and is most likely limited by free RAM on the ESP. I'd recommend using an ESP32 for that.

https://github.com/Aircoookie/WLED/wiki/Compiling-WLED < This is a great starting point for writing your own mods to WLED.
