### ISSUE TITLE
e1.31 Multicast not working

### ISSUE THREAD

**Issue by glitchqc** [Aircoookie/WLED#174]
Hi 
i recently tried your code with e1,31

i manage to make it work with Unicasst (specify the ip address in the software
but when i switch my software to multicast (which is the mode i need) the led stop working and get back to powerup colors.

**Comment by Aircoookie** [comment]
Hi!
It is required to reboot WLED once after switching to multicast. Did you try that?

**Comment by glitchqc** [comment]
Yes i tried multiple times

**Comment by sjude68** [comment]
How do I configure hyperion with wled. Can I use hyperion grabber on Android tv. I have used hyperion installed on Raspberry Pi which worked great.

**Comment by nethoncho** [comment]
I am having the same issue with multicast not working.  unicast works even when the config is in multicast. May be a config issue because wled only binds to one or the other based on the config but not both. [See Code](https://github.com/Aircoookie/WLED/blob/17c20276a9641c31ff7e578e1d54766b79d0942d/wled00/src/dependencies/e131/ESPAsyncE131.cpp#L44)
I am using [sACNView](https://sacnview.org/) as a test harness. I will get a build environment going to see if I can track down the issue...

**Comment by nethoncho** [comment]
Looking through the source I [found this](https://github.com/Aircoookie/WLED/blob/17c20276a9641c31ff7e578e1d54766b79d0942d/wled00/src/dependencies/e131/ESPAsyncE131.cpp#L80). I can not find where n is set.
`for (uint8_t i = 1; i < n; i++) {`
Can someone have a look?
