### ISSUE TITLE
Seeking DEV to help port LED effect to WLED (Paid Bounty)

### ISSUE THREAD

**Issue by nftarts** [Aircoookie/WLED#1894]
Seeking DEV to help port LED effect to WLED (Paid Bounty)

**Comment by huggy-d1** [comment]
Post a link to the source code so people can have a look.

**Comment by Aircoookie** [comment]
@huggy-d1 their code is unfortunately not open source, which of course complicates the matter a bit :)

@nftarts I'm closing https://github.com/Aircoookie/WLED/issues/1877 since it is effectively the same question and will leave this issue open. Feel free to swap if you prever using the original issue.
