### ISSUE TITLE
HTTP/UDP-API: no action of the led strip can be recognized when values are sent below a certain limit 

### ISSUE THREAD

**Issue by JimlyTheReal** [Aircoookie/WLED#1908]
I'am using a 5m SK6812 5V led strip with WEMOS D1 mini ESP8266 and working via http or udp.
I have two problems:
1. If I send &R, &G, &B or &LX values below 28, there is no reaction on the LED, only when values from 28 are sent, but the LED on the WEMOS D1 lights up.
2. I send 0 for &R, &G, &B each but for &W> 28, there is not a single light. Only when R, G, B> = 28 is W represented with 150, for example

**Comment by huggy-d1** [comment]
That means your particular LED strip has a minimum "on", and anything from 1 to that min value (for you that's 1 - 27) is that min brightness level.
If you use a different strip or different style strip, it might have a different min value.
Now that  you know 28 is basically the lowest on, you can scale your output so that 1% = 27, with 100% = 255.  You might even notice a certain brightness above some number close to 255 does not really change the brightness. 
Hope that helps.  It is not a perfect world with these inexpensive LED strips.
