### ISSUE TITLE
Connect Implementation 

### ISSUE THREAD

**Issue by richyxi** [Aircoookie/WLED#200]
Hi, @aircookie i got an idea of how the conection can work more automatically.

So i got a rpi runnin ledFX which work awsome with WLED and my idea is that everything got connected easefully in pretty much any place with internet

 The rpi gets conected and got the avialable IP, and then it got re-connected to the WLED AP to send the credentials of the wifi network and its adresses

The thing Is that how can i send data to the ESP.. i was thinking via sockets but first it would be good if i listen your opinion first on this topic

Cheers!

**Comment by Aircoookie** [comment]
Hi @richyxi !
I really like your idea with the autoconnection! I believe most users won't use WLED alongside a raspberry, but if you want to implement this, it should be easily possible with the current WLED code!
It could work like this: Let the Pi connect to WLED AP. Send a HTTP POST request to `192.168.4.1/settings/wifi`, containing the following arguments: `CS=[network SSID]&CP=[password]`. Optionally you can also use the arguments `I0`, `I1`, `I2`, `I3`, `G0`, `G1`, ``G2`, `G3`, `S0`, `S1`, `S2`, and `S3` to set a static IP, gateway and subnet. Keep in mind that the ESP will reboot after this request!

If possible, I'd rather not add any new protocol to WLED because we are already running into severe memory constraints on the ESP8266. Let me know what you think!

Cheers!
