### ISSUE TITLE
Button gedrückt halten um einen bestimmten Effekt laufen zu lassen.

### ISSUE THREAD

**Issue by Ronny-1979** [Aircoookie/WLED#2087]
Hallo,

mich schreibe mal in deutsch, englisch ist nicht so das es alle verstehen würden.  

Ist es möglich wenn man einen Button gedrückt hält das da ein bestimmter Effekt abgespielt wird?  Nach dem loslassen des Buttons müsste es dann wieder auf die Playlist zurückfallen. 

Gruß Ronny

**Comment by Sturm2002** [comment]
In English,
***
Hi,
i'm gonna write on german, due to my bad english.

would it be possible to play a effect only while holding a button, if i release it, it's gonna switch back to the Playlist

best regards
Ronny
***

**Comment by Sturm2002** [comment]
@Ronny-1979 probier mal die seite deepl.com aus, klatsch da deinen deutschen text rein, und poste hier die englische übersetzung, das ist ein "englischen projekt" auf deutsch zu schreiben bringt hier nix ;D
***
try deepl.com out, write your german text there, and use the converted text to post it here, it's not useful to write on german, because this is a "english project"

**Comment by Ronny-1979** [comment]
Hat sich erledigt, man müsste bloß mal richtig lesen. Über Switch funktioniert es. 

That's taken care of, you just have to read it properly. It works via Switch.
