### ISSUE TITLE
Both .13 betas cause loop reboot on M5stack atom lite

### ISSUE THREAD

**Issue by Kodekat84** [Aircoookie/WLED#2108]
**Describe the bug**
Flashed to m5Stack atom and endless reboot occurs.

**To Reproduce**
Flashed with ESPHome Flasher 1.1.0

**Expected behavior**
Module boots and wifi access point pop-up to configure.

**WLED version**
 - Board: ESP32-PICO
 - Version 0.13.0-b2 \ 0.13.0-b0
 - Format Binary

**Additional context**
Anything else you'd like to say about the problem?

Thank you for your help!

**Comment by huggy-d1** [comment]
Has anyone had success with the ESP32-PICO's yet?  I have only seen problems.  Did you search the discourse site and existing issues for PICO to see if anyone has been successful with that device yet?
This discourse thread may help: https://wled.discourse.group/t/support-for-esp32-pico/265/14

**Comment by blazoncek** [comment]
@srg74 has had success.
He may share info on how on WLED Discord.

**Comment by phluther** [comment]
The available binary for the ESP32 is not compiled for the ESP32 Pico that is used in the Atom Matrix and Atom Lite. If you want to install on the Atom, you need to compile WLED from source using platformio. You will need to uncomment "default_envs = m5atom" in "platformio.ini".

**Comment by Aircoookie** [comment]
Indeed I can confirm the `m5atom` environment works, while the binaries (which are built with the `esp32dev` environment) don't.
I will try to check whether it is possible to make the ESP32 Pico compatible with the standard binary again.

**Comment by srg74** [comment]
I can confirm that latest master is working with ESP32-pico-kit.
<img width="510" alt="Screen Shot 2021-08-06" src="https://user-images.githubusercontent.com/28492985/128563875-2a8536b0-8179-4c53-91ac-1684cd245410.png">

**Comment by blacksanta69** [comment]
> I can confirm that latest master is working with ESP32-pico-kit. WLED 0.13.0-b2 (build 2107230)

I can successfully install 0.13.0-b2 or any v13 beta _only_ on-top of a successful v12.0 write and setting some default configs - e.g. wifi settings. So, I'm guessing this issue is bound in some way cfg.json or the wifi settings not being set and it triggering an error (or I'm missing some other step). I definitely _cannot_ get this running after erasing and then writing v0.13.0-b2 bin with platform.io or esptool; I get the looping error (Guru Meditation Error: Core 1 panic'ed (IllegalInstruction))

Hope this helps.

For me, the current workaround is to install v12, set the wifi settings and then install any v13b

**Comment by jcam** [comment]
This is the still the case, and is also a problem on the newer AtomS3 Lite running either 0.14 or MM. Have to do a custom build to avoid WLED triggering a FLASH_CS reset on bootup

**Comment by epsimatic** [comment]
For M5Stack users: [WLED online compiler](https://wled-compile.github.io/) allows to build and flash *(requires Google Chrome browser)* a customized firmware online.

Setting board to esp32dev, LED pin to 27, building & flashing it online solved the issue for me for M5Stack Atom Lite
