### ISSUE TITLE
UI effects tab: Right Arrow on FX 57 cycles to FX 53

### ISSUE THREAD

**Issue by pete111** [Aircoookie/WLED#22]
Hi @Aircoookie, I found out once you reach 57th effect and click on the right arrow again (it should go to 1st effect), it goes to 53rd effect and then step by step to 57th - so it is not going from start 1st effect once right button is clicked on the effect No 57.

**Comment by Aircoookie** [comment]
Hi Pete,
thanks for the feedback! I didn't notice it before, but I know why it happens now and can fix it.
However, I'm not yet sure how exactly I should set it. I have three options:
- Make it go to Effect 0 (no effect, solid color). Normally you'd use the cross icon for that
- Make it go to Effect 1 (blink)
- Make it do nothing (stay at effect 57)

All of these would be logical behavior. I'm considering the 3rd option since the left arrow also does nothing when at effect 0 (solid color).

Which one do you prefer?

**Comment by pete111** [comment]
Hi @Aircoookie, I thing 3rd option is pretty ok :)

**Comment by Aircoookie** [comment]
Alright, this small change will be added in the next update :)

**Comment by Aircoookie** [comment]
Added in 0.7.0!
