### ISSUE TITLE
16 Bit Color Support

### ISSUE THREAD

**Issue by Differentunic** [Aircoookie/WLED#2252]
I have a couple hundred UCS8904 leds, which are RGBW. I've tried to get them to work with WLED, but the colors see random for the whole length of leds. 

I've been experimenting with getting [FastLED](https://github.com/FastLED/FastLED) to work with RGBW, but the same problem with random colors ocoured. I searched around for datasheets on the UCS8904 Chip, and found [this](https://www.advateklights.com/knowledge-base/ucs8904) site, which shows that they use 16 bits for color.
<html>
<body>

lock Type | Data-Only
-- | --
Color Resolution | 16 bits
Physical Package | SOP8
RGB | See UCS8903
RGBW | Yes
Output Pixel Voltage | 5 – 24V
PWM Rate | 1000Hz
Suitable Camera | Up to 34fps, see Refresh Rate and PWM Rate
Data Transfer Rate | 800kbps
Redundant Data Line | No

</body>
</html>

I'm not the best at programming, bit managed to modify the RGBW code for 16 bits of color, which can be found [here](https://github.com/Differentunic/FastLED/tree/master/UCS8904).

If it's possible would you be able to add a setting in WLED to enable 16 bit color? I'm happy to help with testing changes with the leds, and if need be, help with the programming aspect.

Regards,
Differentunic

**Comment by blazoncek** [comment]
This is really not a request for WLED.
WLED uses NeoPixelBus by @makuna so you should look there if the chip is supported and request support if not.
Once it is supported in NeoPixelBus we may include it in WLED.

**Comment by Differentunic** [comment]
> This is really not a request for WLED.
> 
> WLED uses NeoPixelBus by @makuna so you should look there if the chip is supported and request support if not.
> 
> Once it is supported in NeoPixelBus we may include it in WLED.

Will do. I'll keep you posted on the progress of this. 👍

Regards,
Differentunic

**Comment by huggy-d1** [comment]
A quick search of the NeoPixelbus repo for UCS8904 yielded 0 results.

**Comment by Makuna** [comment]
Goto Github: Makuna\NeoPixelBus and create an issue, find a spec sheet and link it, and I can look into it.  The linked spec sheet isn't a spec sheet, its just a marketing sheet.  Doesn't give a clue about pulse timing.

NeoPixelBus already supports Rgb48Color (16 bits per channel color object), but there isn't a Rgbw64Color (Rgbw version).

**Comment by Differentunic** [comment]
I have no idea how to add a new led type. I did try to just replace the SK6812 with the new UCS8904Feature, but there were errors in the compilation. (this was after updating the libs)

I do actually plan to use WLED for a Christmas setup but can't figure out how to add the 16-bit support into WLED. 

I'd really appreciate it if someone pointed me in the right direction of how to add this support, or wanted to collaborate to make it work. Really looking forward to it!

Regards

**Comment by Aircoookie** [comment]
I too believe 16 bit output is a great step forward - even with only scaling the brightness this will give a noticable benefit to gradient smoothness at low brightness even if we stay with an 8 bit color model in the effect calculation for the time being.

One possible cause for the compilation error you had @Differentunic is that `NeoPixelBrightnessBus` (which is used by WLED) does not (yet) support the new types, the regular `NeoPixelBus` should though. BrightnessBus is kind of a compromise, since it has to scale the brightness on the fly and returning the original color is lossy. Still, it saves some memory compared to the alternative, double buffering. We could try switching to the regular `NeoPixelBus` object in `bus_wrapper.h` for testing.

**Comment by Differentunic** [comment]
> We could try switching to the regular `NeoPixelBus` object in `bus_wrapper.h` for testing.

Is there some documentation surrounding how I would go about replacing it with the regular NeoPixelBus, or are you able to do it?

**Comment by Makuna** [comment]
Note, there is an example in NeoPixelBus on how to implement a brightness bus using a shader technique.  The NeoPixelBrightnessBus was provided for backward compatibility to Adafruits; but I always suggest the shader as it give the sketch writer more control on how brightness is applied.

**Comment by blazoncek** [comment]
It will be possible to use WLED with UCS890x chips with the (next) release of NeoPixelBus v2.7.3
See https://github.com/Makuna/NeoPixelBus/issues/638

Many thanks go to @Makuna for fixing NeoPixelBrightnessBus.

**Comment by blazoncek** [comment]
Even though WLED does not natively support 16-bit color depth, it can utilise 16-bit LED pixels using on the fly up-scaling. Some 16-bit LEDs were successfully added as supported in 0.14.

Closing as it may not be feasible to update core to work  with 16-bit color depth.
Feel free to reopen if you find good justification otherwise.
