### ISSUE TITLE
MQTT retain setting

### ISSUE THREAD

**Issue by Aircoookie** [Aircoookie/WLED#2263]
**Is your feature request related to a problem? Please describe.**
WLED MQTT messages are mostly retained, this could lead to broker storage issues and/or annoying residual messages.

**Describe the solution you'd like**
A checkbox for setting whether publishes from WLED should retain or not.

**Describe alternatives you've considered**
Editing mqtt.cpp

**Additional context**
By Karl_S via Discord #learning

**Comment by blazoncek** [comment]
I would assert that retained messages are a bad habit, especially since there is no user friendly way to remove obsolete retained messages.
There are some justifications for them (i.e. quicker last known state retrieval, etc) but potential problems out-weight them.
Perhaps adding periodic _state_ messages (1/min) could be used instead.
It has to be noted that many (and/or large) MQTT messages may yield dropped frames.

**Comment by blazoncek** [comment]
Ordinary people don't use MQTT Explorer.
They should have no need to as well.

**Comment by blazoncek** [comment]
There are 3 topics that are retained: `/g`, `/c` and `/status`.
As status is also LWT it should not be non-retained.

My proposal is to remove retain options from `/g` and `/c` topics altogether.
