### ISSUE TITLE
Can't set preset via JSON_API

### ISSUE THREAD

**Issue by sogeniusio** [Aircoookie/WLED#2283]
I've looked through the WIKI and can't seem to find anything that could help with this issue I'm having.

I'm trying to set a preset programmatically but I'm getting no response from my lights. When I run a GET to /json/state I get all the details back:

```shell
☁  ~  curl -X GET "http://10.90.4.34/json" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3137  100  3137    0     0  33154      0 --:--:-- --:--:-- --:--:-- 38256
{
  "state": {
    "on": true,
    "bri": 255,
    "transition": 7,
    "ps": 7,
    "pl": -1,
    "ccnf": {
      "min": 1,
      "max": 5,
      "time": 12
    },
    "nl": {
      "on": false,
      "dur": 60,
      "fade": true,
      "mode": 1,
      "tbri": 0,
      "rem": -1
    },
    "udpn": {
      "send": false,
      "recv": true
    },
    "lor": 0,
    "mainseg": 0,
    ...
}
```

But when I run a POST `curl -X POST "http://10.90.4.34/json/state" -d '{"ps":5}'` nothing happens. I'm running WLED version 0.12.0

Edit: Even when I run: `☁  ~  curl -X POST "http://10.90.4.34/json/state" -d '{"on":false,"bri":0}'`, I also get nothing

**Comment by Aircoookie** [comment]
Just checked again because the wled webserver doesn't enforce content-type `application/json`. Specifying `text/plain` will work too, if the `-H` option is not used though, curl will use `application/x-www-form-urlencoded`, which the server interprets as form data and not JSON and will thus return error 400. Added a curl example to the docs :)
