### ISSUE TITLE
OTA from 10.0.2 -> 13.0-b4 Bricks NodeMCU

### ISSUE THREAD

**Issue by EmonFan** [Aircoookie/WLED#2293]
**Describe the bug**
NodeMCU V3 (With CP2102) with 60 leds (12v) Manual OTA from 12.0.2 -> 13.0-b4 bricks the mcu.

**To Reproduce**
Running firmware 10.0.2 -> Manual OTA with WLED_0.13.0-b4_ESP8266.bin
Displays success message but NodeMCU and leds are 'frozen'. Can't recover with power cycling.
Need to get cable out I guess ;) 

Bricked two so far. I have 22 to go :)

Can successfully update if I go from 10.0.2 -> 12.0.0 -> 13.0-b4

**Expected behavior**
Expected update to succeed.

**WLED version**
 - Board: NodeMCU V3
 - Version 0.13.-b4
 - Format: Binary

**Additional context**
Awesome work gang!

Thank you for your help!

**Comment by Aircoookie** [comment]
I could not reproduce a situation where the device was bricked due to an update from 0.10.2 to 0.13.0.
A freshly erased ESP8266 was flashed with `WLED_0.10.2_ESP8266.bin` via esptool, WiFi and LED count configured and then OTA updated to `WLED_0.13.0-b4_ESP8266.bin`.
The configuration remained intact _with the exception of LED count, which resets to 30_.
Same behavior with ESP32.

@EmonFan can you try connecting the unreachable ESP to a Serial terminal (e.g. in VS code or the Arduino serial monitor). Does it bootloop? (in that case it will print the same message over and over again)

**Comment by EmonFan** [comment]
Hi, yup stuck in a boot loop.

`xception (3):
epc1=0x40101231 epc2=0x000003ffffe002198c7
3d0 00000003 3423f
3ffffe50:
3ffffx00000000

>>>stack>>>

ctx: cont
sp: 3ff3fffffc0 offset: 0190
3ffffdc0:  00000000 80800000 01040000 0000ff0f50:  0001c200 0000001c 3fff0e98 3>
3fffff60:  3fffdad0 3 feefeffe  e:(3,7)
`
