### ISSUE TITLE
LED color glitches/flashes

### ISSUE THREAD

**Issue by coelner** [Aircoookie/WLED#230]
Hey, 
I use 120 WS2812 wit a 4A 5V power supply (limit 3800mAh). The firmware is 0.8.5 on two different ESP8266 boards. I want to use a self soldered ESP12E board with minimal space requirements. With this board I have some LED glitches. Most of the time the selected color is shown, but randomly short burst with a different color appears. A single level shifter is also used, but the led stripe works flawless with a nodemcu even without a level shifter. 
If I set the brightness the glitches don't appear, all other glitches are with full brigthness. If I use only a red color, those glitches are mostly green, sometimes blue. Most of the time the complete stripe is affected, but sometimes only the first LEDs burst the wrong color.

Any hints where to search for solving the issue?

**Comment by theshadowsvk** [comment]
Hello,
please, which pin/method are you using ? Are you sure that voltage drop is not big ? Sometimes this could be the issue of random color glitches.

**Comment by coelner** [comment]
I use GPIO2. I flashed it with a CH340G directly over the gpio pins and took this one: WLED_0.8.5_ESP8266.bin
Which voltage drop do you mean? with full brightness it is 4.9V and at end 4.2V (With power limit set to 3800mA). But this should not be a problem, the nodemcu can be used for this and there are no glitches at all (at the end 3.8V)

**Comment by theshadowsvk** [comment]
Hmm okay, can you drop schematics of your board ? This sounds like other
problem

Dňa pi 27. 9. 2019, 8:39 coelner <notifications@github.com> napísal(a):

**Comment by coelner** [comment]
![IMG_20190927_093729145_HDRlow](https://user-images.githubusercontent.com/16364254/65752936-277ff600-e10e-11e9-806f-43a1f75b7f51.png)

**Comment by theshadowsvk** [comment]
One question, is the common ground shared between 5v and 3.3v line ?

**Comment by coelner** [comment]
Yes, it is.

**Comment by Aircoookie** [comment]
Your setup looks good to me. I actually believe that this is indeed a software issue because I have had it too on two of my lights. I was suspecting that the reason was a missing levelshifter, but might be an occasional flipped or dropped bit in the UART after all.

**Comment by coelner** [comment]
I'm not sure. The nodemcu works well even without a levelshifter. At least I get there no glitches. And the single ESP12 feels hotter than the nodemcu (measured with my finger tip...) but this could be the missing pcb underneath.
I assume two issues, one with flipped values in the UART, but somewhere a hardware vault.
https://streamable.com/o8lsz

**Comment by Aircoookie** [comment]
Thanks for the video! For me it looks exactly the same, albeit at a much lower frequency at one glitch per 20-60 minutes, not every few seconds. This indeed seems like more of a hardware issue, but since there is no hardware difference with the pin between ESP12 and NodeMCU I can't see where. Did you try without the levelshifter? I've recently heard that some models modify the waveform enough to cause issues.

**Comment by coelner** [comment]
Yes, I added the level shifter after these glitches appear. 
Those esp12 are mass products, maybe something is broken inside (which would explain the hotter surface). sadly I have no oszilloscope otherwise I would inspect this furthermore.

You can close the issue and leave a reminder if LEDs are flickering that it is maybe a direct hardware issue.

**Comment by coelner** [comment]
Ok, even the nodemcu has got the glitches, but more like one in a hour.

**Comment by frustreermeneer** [comment]
I'm experiencing the same random flashing problem with 249 LEDs on an older Lolin NodeMCU on pin D4/GPIO2. 
I didn't have this problem with FastLED on another GPIO pin.

**Comment by kcoop99** [comment]
Experiencing the same issue. Random color flashes. Running 12v lights. Has this been determined to be hardware only?

**Comment by kcoop99** [comment]
Swapped my wemos d1 mini for a node mcu and am running into same issue. Leads me to think it's software and not hardware.

**Comment by wardwygaerts** [comment]
My leds seems to flicker all together when changing color. Will make a video tomorrow.

**Comment by dhami220** [comment]
I get the flashes as well (every few seconds) with couple interesting observations below.

My setup: Two LED strips controlled by two nodeMCUs, two level shifters and 40amp power supply.

1) If only one LED strip is running, I don't get any flashes.
2) If I turn the second LED strip on, the flashes appear.
3) If both LED strips are set to halloween, no flashes. If have tried other effects, but only found halloween working without flashes.

**Comment by dhami220** [comment]
Tried a few additional items without success:
- I have wire nut on the data cables. Replaced that with soldered joint. Same result.
- Removed level shifter (connected directly to nodemcu). Same result.

Next steps: 
- I have two small strips. Going to give those a try right next to mcu to rule out data cable length and/or excessice number of LEDs on my main strips (~320 per strip is what i have. the small ones have ~20 LEDs).
- I have seen some posts about capacitor. Will give that a try if I can find a similar capacitor.

**Comment by kcoop99** [comment]
Can anyone confirm or deny that a logic level shifter DOES work???

**Comment by theshadowsvk** [comment]
Yes I'm using it, without any problem

**Comment by kcoop99** [comment]
Would you be able to share which one you are using and how you have it wired?

**Comment by Physikus74** [comment]
Hello,
that sounds to me like EMV problems, or actually voltage dips due to pulsating currents in the effects. A good buffering with capacitors near the MCU should help. It is even better if the MCU gets its own power supply. So the "big power supply" for the LEDs can be switched from the MCU and the MCU itself is independent from the currents of the LED's. When designing the GND line you have to be careful that the current through the LED's does not influence the voltage of the MCU! For me such a setup with more than 900 LED's works very well.

**Comment by palengh** [comment]
Thank you for your great effort with this project. I really appreciate it.
I too experience the random flashing of the lights.
Running WLED 0.8.5, and using a 5 m 300 LED strip. My power supply is 12V (12.5 A) directly to the LEDs sharing the common ground with the NodeMCU. My NodeMCU has D4 connected to the
LED´s program wire. When setting Max current to 12500 mA, the LEDs flashes like strobe light. I need to set the LED Max current to below 2000 mA, to stabilize it, but even then it will flash randomly. When I disconnect the D4 connection, it's stable, even at 12500 mA.

The D4 connecting cable is 8 cm long.
Setting "skip the first led" in the configuration dit not help

**Comment by austwhite** [comment]
I am using WS2811 LED's and I get the flickering issue quite badly when using default GPIO2 or GPIO3 for the LED data.  Strangely, the flicker only happened if I set the current to above 1000mA.  If I limit the brightness, no flicker at all.
I decided to play with this.  I changed to use GPIO14.  The compiler warned me it would use software bitbanging which may cause flicker, but the exact opposite has happened.  The flicker I was previously getting is now totally gone.  Even at full brightness no flickering.  
It isn't a hardware issue either as I have used 3 different D1 Mini's to test with (one was a D1 Mini Pro, genuine WEMOS, two are clones).
I haven't got a WS2812 to play with at the moment, so I can't comment on that, but on the 12V version WS2811 I have this seems to have solved the flickering completely.

**Comment by mdscarrott** [comment]
#87 led me here. I have the same issue as many. 
12v WS2815
Using ESP32 dev board
No logic shifter required - i actually tried a falcon f-amp initially but this caused a flicker whenever changing colour - once removed all was stable. 

All worked well when using 193 pixels, now i have added some more (with necessary power injection from same supply with plenty of power) i get flickering, almost like a flash every so often. The frequency is different based on which effect is used.

I found the 'pride' effect a good test as this makes it flicker/flash very quickly. Something like twinklefox only every few minutes.

What is strange is that it is only really affecting the last 203 pixels, not the first 193. These numbers also coincide with what was seen in #87 

Please let me know if i can provide any more info.
Matt

**Comment by austwhite** [comment]
The flicker you are describing sounds like what I had when I was not using Ng a logic shifter over a long run.
I know the LEDs are supposed be repeaters for the data line, but my issue was fixed by adding a logic shifter so the LED strip was using 5volt logic.

**Comment by austwhite** [comment]
My flickering issue is resolved in the latest versions, as long as I use a logic shifter.
As soon as I remove the logic shifter, the flicker returns toward the end of the strip.
I know the LEDs are meant to be data repeaters, but this issue definitely seems related to logic level for me.

**Comment by kcoop99** [comment]
I can't recommend enough the QuinLed Uno boards. Eliminates every possible issue in my opinion.

**Comment by meekell** [comment]
I ran into the same issues as many have described here while running my under and top cabinet light strips. Each is controlled by a separate nodemcu. I determined the issue to be due to signal coupling between the two data signals. When running more than one data signal together, make sure you have sufficient wire separation so that the radiated emissions are not picked up by the other wire.

**Comment by rayperkins1** [comment]
I am having this issue now, I noticed when I am touching the signal wire the flickering goes away.  I tried adding a capacitor to between D4 and GND, but that stops all color changing.  Maybe I need a smaller capacitor, but I only have a few on hand to try.

Any other ideas?

**Comment by rayperkins1** [comment]
I read the uber guide to neo pixels on ada fruit and realized I needed to add a resistor between the ESP8266 signal pin and the data in on the LED string, now it works great.

**Comment by rawframe** [comment]
Prob1 : **Mostly random flickers and colours.**
Fix : Make sure the circuits share the **same ground** (i.e. esp and lights have a common ground connection)
Prob2 : **Random flashes intermittently**.
Fixed by powering the esp unit via the 5v input and not 3.3v. (Perhaps transformer introduced noise/voltage fluctuation, or **isolation/stability of gpio is better via 5v input**) . Didn't try **@rayperkins1** solution but could work in a similar way.
[Wemos D1 mini & 5v SK6812]

**Comment by austwhite** [comment]
Using a module such as the QuinLed Dig Uno will ensure your ESP device runs off 5V correctly, but be aware some cheap clone devices are not as stable as others.
I had a couple of cheap clones and they would flicker occasionally but my genuine D1 Mini Pro's have always been rock solid.
Sometimes the clones are just not stable enough to keep up with WLED.

**Comment by noloco** [comment]
I'm having the same issue with 12v LEDs

**Comment by austwhite** [comment]
I have just been playing with Hyperion and WLED and have noticed regular flashes on the WS2811 strip I have as my test strip.
It happens when using UDP (Raw) or E1.31 protocols.
It seems to just randomly flash sections of the LED strip to full brightness for about 1/4 of a second then drops back to normal brightness.
The colours are not changed, it just seems to randomly flash random sections to full brightness.

**Comment by olliegg123** [comment]
Was this fixed with certainty? Any ideas for mine? 

This is on Twinklecat: https://streamable.com/7g1ji0

I notice that it happens more frequently when the brightness is lower.

**Comment by rayperkins1** [comment]
Adding the resistor 100% fixed it for me.  Not sure if you have other problems, but make sure you have a resistor inline, and maybe try a few different values if you already have one.

**Comment by olliegg123** [comment]
Which like did you put the resistor between?

**Comment by kcoop99** [comment]
I got fed up and finally bought quindors dig Uno boards. Fixed it for me. Before that however I used a logic level shifter and that fixed it too. You can use a sacrificial pixel too.

**Comment by Aircoookie** [comment]
Yes, just to confirm, this is a hardware problem, not fixable in software. The most solid solution is indeed using a levelshifter (like the SH74AHCT125N utilized in the QuinLed Dig-Uno board), however reducing the supply voltage of the first LED by a volt using a diode also works nicely.

**Comment by olliegg123** [comment]
Thanks for all the help. @kcoop99 , what do you mean by a sacrificial pixel??

**Comment by Aircoookie** [comment]
@olliegg123 a single pixel directly at the microcontroller output to boost the signal. Sometimes even that is still unreliable, in that case adding the voltage drop diode helps.

**Comment by kcoop99** [comment]
@olliegg123 try this.
![0D6B5CC0-7BC4-4321-A3EA-50D702D6A9F6](https://user-images.githubusercontent.com/55409439/82757894-e6c5a300-9da8-11ea-80f7-2bd7253231ea.jpeg)

**Comment by olliegg123** [comment]
Perfect. Thank you both. I’ve ordered a new 5V 5A power supply (was originally stepping from 12v to 5v) so will try it out tomorrow with a sacrificial LED which will hopefully work.

**Comment by fishbone-git** [comment]
I'm interested to know if anyone is seeing this WITH the QuinLED dig-uno.  I upgraded to get around this problem, and it's still present.  Some effects work, some can work if they are set at power on, others never work.

**Comment by Aircoookie** [comment]
@fishbone-git is this with the D1 mini or the ESP32? What are some examples of working vs. flashing effects?

**Comment by fishbone-git** [comment]
Mainly ESP32, but I also tried a D1 Mini as a test (they don't stay connected to the wireless well enough so don't use them regularly).  Pacifica seems to be consistently good.  The Comet effects are ok, but only at lower brightness.  Oscillate is bad as is any of the twinkle/glitter effects.  Noise 1 and 2 can be made to work if set at power on.  Noise 4 is never ok.  It also seems to be worse when red is involved, but that is more of a subjective view.  In general, cooler colours with slow rate of change.  Odd, as I expect the control signals are the same regardless.

**Comment by fishbone-git** [comment]
Hey, an interesting data point:  I had a go a dialing into the failure on one of the strings.  I started at the first LED where it fails.  Pressing down hard on the LED makes it work, then I had to do this twice more on the string.  To help hold this "pressure", I've taped those LEDs with clear tape.  So, this hints at local LED issues, perhaps temperature or cold soldering.  The really interesting bit is that after fixing the one string, the other three magically cleared up! Oddly, the string I fixed is the "master" which syncs the rest over UDP.  I can't even suggest a wacky theory here.

**Comment by olliegg123** [comment]
Sacrificial LED worked perfectly (so far)! I didn’t have a diode, so it’s running without one at the minute but I’ll be putting one in once I get it. Thanks for the help!

**Comment by fishbone-git** [comment]
Another experiment: I went back to 0.9.0-b1 as this was the oldest binary that I have with my pin config and I was able to run Oscillate for 20 minutes without an issue.  Flashing back to 10.0 and immediately on starting the effect, the leds went bad.  I also have another string running twinklefox.  10.0, there is a bright flash of white (sometimes green) every few minutes.  with 0.9.b1, no issues at all. No doubt that there is a hardware issue in the string a couple of posts ago, but it's not the whole story I think.  Also, when it goes, it takes all other strings in the led group with it so that it still very odd.

**Comment by SamPhoenix91** [comment]
I have been having this issue and found that changing the power supply fixed it. Maybe a power regulation issue?

**Comment by SHolman77** [comment]
Qa

**Comment by wilson3682** [comment]
Hi all, I was having the same problem with the flickering lights when using the wemos D1 mini. All the problem came down to the weak voltage regulator the manufactures are using on this boards. I found the solution here:
https://www.reddit.com/r/esp8266/comments/c2vhvy/update_best_solution_to_the_wemos_d1_mini_weird/

I Added the AMS1117 regulator as seen in the picture and now all flickering is gone! I hope this can help somebody else having the same issues.

**Comment by coelner** [comment]
That is a fake wemos board, the esp12 and the pcb. You said that the ME6211 gets you into the brown-out, maybe the MIC5219 LDO is better. At least it has a reverse current protection. But so far, I did not get into the brown out with the original wemos boards.

**Comment by Model-Man** [comment]
Not experienced this on any of my 4 clones however cheaper regulators may well drop below 3.3v under load and this is where it counts.

**Comment by wilson3682** [comment]
Yes guys I agree with you, this only happens with the cheap, clone or fake ones that are being sold everywhere. Another thing I have to mention is when I use these clone or fake boards with wled they work perfectly, the problem arises when I try to use the UDP and E1.31 protocols from Hyperion.ng and X-lights, half of the strip starts flickerin. This does not happen when I use the good ones like the ESP8266 NodeMCU boards

Cheap ones: https://www.amazon.com/gp/product/B076F52NQD/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1
Good ones: https://www.amazon.com/gp/product/B081CSJV2V/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

I only wanted to share my experience with these boards in case someone else was having the same issues. If you have the cheap ones and you are experiencing the same problem as me, it's up to you if you want to try the quick fix, if not just buy the good ones and you are good to go.
Cheers!...

**Comment by Model-Man** [comment]
Further to my comment regarding no issues with D1 mini clones, I have now discovered this problem on a string of 
100 WS2811 led's running along an outbuilding.
Like others a sudden strobe affect occurs across the whole chain of led's. It never seems to effect blocks or single led's. The strobe effect is usually at full brightness and mainly white however other solid colours have also been noticed.  It happens at random times often going minutes without anything then several strobes during a single sequence. It can happen during a transition of presets or running a single pattern. Very noticeable when using the "sparkle dark" effect but also happens on others.  
Reading all the comments it seems there is still no positive remedy. Taking everything into account and eliminating the
Wled software out of the equation, it must be either the controller or the influence of something around the controller such as induced noise.
I intend to do some testing shortly using various combinations and setups to see if I can recreate the problem on another
controller on the bench. Hopefully I can then reverse engineer a fix. I only use high quality converted PC power supplies
so I can eliminate noise from the 5v source.

I will update with any findings

**Comment by Model-Man** [comment]
Update. 
 After several hours of testing I was able to recreate the glitching effect on the bench using a second D1 mini clone.  This was done by gradually extending the data line until the whole chain began to flicker. Extending the data line further made the flicker more frequent up to the point where constant flicker occurred while running a sequence.
One thing I did notice was the problem happened at different data line lengths on different clone controllers. 

The fix so far

Going back to the problem controller I began testing using different combo's such as the diode trick, varying the voltage slightly, ferrite beads, data line screening and a data line amp. Below is the combo that has worked so far on a data line of up to 4m. 
As you can see I've simply used the diode trick but added an additional 330R resistor on the output data line. I have tested this so far for 5 hours with no noticeable strobe issues. I will continue testing as the lights run 5 hours each night on my outbuilding. I'm not claiming this is going to work for you as there are often other variables that can influence the results however for a cost of next to nothing it might be worth a try. 


![Wled-Test](https://user-images.githubusercontent.com/69106021/91657829-41fbe580-eabc-11ea-9dbf-12af595d689b.jpg)

**Comment by Svrbinek** [comment]
Hi, I'll try to describe the flicker problem with me. I want to use LEDs for stair lighting and so it is a total of 15m type SK6812. The power supply is used 5V 60A, ie strong enough for operation. WLED is installed on ESP32 WROOM full version (large).
Flashes of different colors appeared to me randomly with certain effects, and even if white was on, the green LEDs flashed.
However, I see the biggest problem when using the WIPE effect, where the first two LEDs flash when they are to be off and, conversely, they go out when they are to be lit. I thought there was a problem in the 1m LED strip, so I swapped the first and second strips and the result is the same, so it has to go from ESP and WLED. I have no idea yet whether this is a problem of HW ESP32 or SW WLED. I also tried to buy a logic level controller, both an 8-line Texas Instrument and a 4-line KeeYees. TX did not work at all according to the delked connection, only with a strange and illogical connection, but the flickering was still. KeeYees arrived today, so I tried it. It worked right away, but again, there's no difference between getting involved with him and without him.
I use the latest version of WLED 0.10.0 and a total of 900 LEDs are used, which are mostly grouped into a 15 group with the WIPE effect.
I find that color flashes appear from the 4th meter. The first three are almost clean, except for the first two LEDs. It also didn't help to turn off the first LED in the settings.
If you are interested, I will make a video.

**Comment by Svrbinek** [comment]
Hi, so it is solved successfully today, thanks to the author, because today I found out that the update is WLED 0.10.2 and it fixed everything, so for now it finally works as it should. It is possible that for SK6812 the earlier code may have caused bad timing with certain effects. Who knows...

**Comment by Svrbinek** [comment]
So I greet again and I have to write another knowledge from flashes again. I used the original bin file and the flashes are not. Then I used the compiled code modified by usermod and the flashes are, so I tried to compile the unmodified files without usermod and the flashes are again. I compile in Arduino IDE. Compilation seems to cause a problem that causes flashes. Therefore, I would like to ask, what are the original files copied from the WLED site?

**Comment by Legsmaniac** [comment]
> I compile in Arduino IDE. Compilation seems to cause a problem that causes flashes.

Have you fully updated everything in Arduino IDE?  If so, that there, I very strongly suspect, is your problem.  Aircookie does not use the latest updates for everything as described in PlatformIO.  Which is why it's better to use PlatformIO rather than Arduino IDE.  For example, he uses NeoPixelBus version 2.5.7, FastLED version 3.3.2 and so on.   And sometimes different versions for different boards.  You also need the exact correct board settings in Arduino IDE.  There's  link somewhere explaining all this better, I'm sure someone will post that link for you soon, if it helps.

**Comment by Svrbinek** [comment]
> > I compile in Arduino IDE. Compilation seems to cause a problem that causes flashes.
> 
> Have you fully updated everything in Arduino IDE? If so, that there, I very strongly suspect, is your problem. Aircookie does not use the latest updates for everything as described in PlatformIO. Which is why it's better to use PlatformIO rather than Arduino IDE. For example, he uses NeoPixelBus version 2.5.7, FastLED version 3.3.2 and so on. And sometimes different versions for different boards. You also need the exact correct board settings in Arduino IDE. There's link somewhere explaining all this better, I'm sure someone will post that link for you soon, if it helps.

Thank you for answer. This might make sense why this is happening. I'm trying to use the PlatformIO platform, but for now it's impossible for me to compile a project in it. I haven't found a video anywhere that outlines how to compile such a large project. But maybe I'll try it and then it will work.

**Comment by 0rsa** [comment]
I join the discussion.

Flickering using 418 SK6812 Leds (RGBW) with 5V/40A power supply from BTF-Lightning.

If I set brightness to 20%, it works fine.
If I launch Hyperion Android Grabber, it works fine using 100% brightness with demo screen (RGB rotation, there is no white, maybe a clue?).

I use WLED, there is no flickering using solid color or effects @ 100% brightness.

I also suspect a software issue.

**Comment by 0rsa** [comment]
Solved.
I disabled 'automatic brightness limiter' in WLED > Settings > LED Preferences and flickering is gone.

**Comment by jonwilliams84** [comment]
What diode is required for the sacrificial LED option? 

I have found 'Skip 1st LED' and turning off the Automatic Brightness limiter in WLED settings helps but still get the occasional flash of white across all LEDs when using with Hyperion.

**Comment by DevPieter** [comment]
You need to give the nodemcu more power that fixed the problem for me.

**Comment by jonwilliams84** [comment]
> You need to give the nodemcu more power that fixed the problem for me.

I have shortened the cable between the esp and the LEDs by 50cm...flashes have disappeared.

**Comment by J-gazm** [comment]
I am running 0.10.2 on a NodeMCU and was experiencing the same random glitching/flashing.

I was able to resolve this by adding a 560Ω resistor inline between Data4 and my LED string.

Seems too simple, but effective, at least for me.

**Comment by qai-retired** [comment]
I am running 0.10.2 on a Dig Quad and was experiencing the same random glitching/flashing.

I was able to resolve this by using 16awg wire for longest data line (approx 18m length)  i have three other shorter runs using 20 awg. Also had to close Android App. Having Web UI open would cause glitching. Once I close UI the gitching would stop.

Only minimal testing done at this point.

**Comment by kuno23** [comment]
Hi, i have the same flickering problem with wemos d1 mini pro, i using 3 strip 1 with nodemcu without problem, 1with wemos d1 mini without problem, and now i bought wemos d1 mini pro, because of external antenna connector for better coverage, but it seems that it will not work with the board..  I tried almost everything all pins, all pins with many value of resistors, power supplies, separate power for board and strip, one power supply for both, but nothing works.. The flickering is so annoying.. I think there on the board are some issues that cannot work with led strip, but for another appliances it can be used without any problems.. Strange problem..

**Comment by J-gazm** [comment]
Another solution I found to the constant glitches/flickering and flat out no control, was making sure the same ground that is connected to the LED strip was also connected to the Node MCU.

For example, I had a 12vdc power supply powering my 12vdc LED strips, and a 5vdc step-down converter between my 12vdc power supply and my Node MCU.

When my LEDs were grounded to the power supply and the Node MCU grounded to the step-down (even though that was connected to the same power supply), I had no control and much chaos.

Once I added my power supply ground to the Node MCU it worked perfect.

The same would be true if you are using two different power supplies, one for the LED's and one for the MCU.  Add a ground jumper from the LED power supply or strip to your MCU.

**Comment by zumdar** [comment]
has anybody had this same problem of flickering but with DMX out? I am sending dmx to a led decoder like [this](https://www.amazon.com/GIDERWEL-Decoder-Controller-DC12V-24V-Channel/dp/B07BVLXWD9/ref=sr_1_7?dchild=1&keywords=led+decoder&qid=1610006694&sr=8-7) to control three 12 volt RGBW led strips. I get lots of random flicker, but i can indeed control the lights via wled..it just flickers like every 5 seconds.  i am outputting dmx on pin 4 so it shouldn't interfere with the default pin 2 being used for led output..

**Comment by Riggaa** [comment]
Just commenting to say that I've had this issue on 3 separate circuits and boy do I wish I knew of this problem before implementing.

I can stabilize the flashing by minimizing the maximum current. 

I have discovered that applying physical pressure on whatever LED is causing the issue, makes the problem go away. 

I have also discovered that removing the problem LED from the circuit allows for the LEDs down the line to function properly.

There doesn't appear to be a true root cause established. 

This is not a standard set up issue, something in inherently wrong in the recommended design/set-up when using as explained and intended. Perhaps the LED strips that I've purchased from BTF are shitty, or ALL of my 5V power supplies are bad.... I feel like the "influences" of the whole addressable LED community need to address this issue.

**Comment by breuerfelix** [comment]
i was suffering from random flickering aswell and i put in 10 hours to solve this. but i wanted to solve it without soldering some other components to it. why ? because everything was working with wled but not with hyperion. (i even had flickering with solid color)
my setup: esp + wled + 5v led + hyperion.

things that made flickering better:
- setting hyperion capture hz and all smoothing update hz to the same value. the lower the better. at 10hz it was usually flicker free but it was a bit laggy. (now i run at 30hz without flickering because of the next steps)
- only solder your power / data lane to one side of the leds. even though it worked when i soldered both ends together, i had better results with only one side
- get a seperate power supply for your leds and your esp. i wanted it to work with one, for real, but this just resulted in less flickering
- GET GOOD WIFI FOR YOUR ESP !!! (also on whatever hyperion runs)

the last step solved flickering 100% for me (haven't tested with smoothing hz above 60 tho, but i am happy as it is)

how to get good wifi?
- move your esp close to the wifi (same with the hyperion device)
- go to your router settings and change the wifi channel. there are lots of smartphone tools that check the wifi channels from your neighbor routers. take a channel which is far away from the routers which are close to you. this results in much better stability with less latency of your wifi devices in general

**Comment by Riggaa** [comment]
I can almost guarantee that Wifi signal has nothing to do with the issue described above.

**Comment by mkovero** [comment]
Never say never, Some pins (GPIO2,23 and so) are described to be used with ADC2 which is known to behave badly/sharing pins with wifi, even though the pins configured here are for digital signal I would try simply to use other pins that are not used with ADC2 to make sure it isn't related.

![image](https://user-images.githubusercontent.com/22191732/126557378-2dae4548-a8bd-45b0-bff8-272b8399831b.png)

**Comment by overcro** [comment]
Hello, i had a very unpleasant blink with every color change, disable crossfade option to fix my problem

**Comment by algovera** [comment]
Same here and I am using BFT strips from China.

I have independent power supply (5V40A/200W) and flickering is more frequently when my ESP32 is placed closer to the power supply.

Does anyone know if Power Supply / transformer should be kept away from the controller by a certain distance?

**Comment by kettenbach-it** [comment]
Maybe my findings will help: I had very strong flickering in brightness and colors as long as I had the Wemos D1 Mini (clone) connected to my computer via **USB** and it was powered via USB and the LEDs were powered by a power supply unit.
After I made the power supply uniform with the power supply unit, all the disturbances were gone. Even if the USB still is connected.
I suspect there was a **ground loop** via the USB bus between the ground of USB and LED which caused at lot of noise.

**Comment by kettenbach-it** [comment]
This is a signal where there's a common ground between USB and LED:

![image](https://user-images.githubusercontent.com/7711872/141617461-87afd5e4-d32b-4e0f-ad99-0817c9011ecc.png)


And this is the same without a common ground:

![image](https://user-images.githubusercontent.com/7711872/141618121-a2ec2479-5c76-4a33-a524-f850bc08099f.png)

You can clearly the distortion and noise.

After bridging the ground PIN of the Wemos with the ground wire of the LED - or removing the USB and fully powering the Wemos D1 by the power-supply of the LEDs => all works well.

**Comment by algovera** [comment]
@kettenbach-it 

Thanks for the information.  I think that explains my situation as well.
I was able to reduce the issue, by enlarging the common ground with a bigger wire.

For my setup,  I actually have an independent power for ESP32 via USB, and use ESp32's relay to control the power-supply of LED, to reduce standby power consumption of the power-supply.

I will try putting esp32 and power-supply together and see if the problem will go ahead completely.

**Comment by algovera** [comment]
@kettenbach-it 
Can you share more information on how you bridge the two?  When I bridge grounds esp32 and led power-supply, I still have flicker, bigger wire helped but does not completely make flickering go ahead
> After bridging the ground PIN of the Wemos with the ground wire of the LED

**Comment by kettenbach-it** [comment]
Just connect the GND from the LED strip to the GND-PIN of the Wemos Board.
If it still flickers it might be something else.

**Comment by jnpatrick99** [comment]
I experience strong flicker and white flashes. I found it seems to depend on the LED Configuration, for example when brightness is low, and "Make a segment for each output" is on it flickers much more (every second). When it's off it flickers once in 15-20 seconds. Also different effects produce different flicker times. On Solid color there's only a few flickers.

So to me it looks like it's software rather than hardware. After I change parameters sometimes the flickers disappear completely.

It started only with recent updates and multiple LED strips support. When I had one strip and older firmware there were no flicker at all. Now I have three (~250 LEDs each).

**Comment by Model-Man** [comment]
Are you using any type of level shifter on each individual output?  If not you should to stop the flickering.

**Comment by BarrettLowe** [comment]
I found that this happens when I've got two segments using the same set of LEDs. I had segment A running leds 0-170, segment B running leds 0-100, and segment C running leds 100-170. Segment A was on (solid), while B and C were running effects and I was getting a flash, what seemed like, precisely once a second. Maybe this helps someone but perhaps software should handle this situation.

**Comment by SteveoMS** [comment]
I am running two BFT WS2815b 144 pixels 12v and I get a flicker of white every fews seconds. I have the 0.13.0-b6 toki running. ground is shared mentioned above. I am power injecting both strips now but same issue. One strip seems to work fine.

**Comment by Riggaa** [comment]
I think that this issue is largely derived from the LEDs simply running too hot and failing over time. I had the flashing issue after awhile for all of my 60LED/m SK6812 RGBWW strips. I switched to 30LED/m and haven’t had a failure yet. I believe that the higher populated LED strips get hotter and due to having double the SMD components/m there is a higher chance of failure.

**Comment by jnpatrick99** [comment]
In my case it's definitely not the strip being hot. I'm not sure why I need level shifter but I was able to suppress the issue by randomly changing modes many times on the strips. Now I have 3 strips, 250 LEDs each, connected to the same ESP32 on almost full brightness, they never flickered since then. Now I'm scared to change any WLED parameters though.

**Comment by Bascht74** [comment]
I have some flicker as well with my quinled quad and WLED 0.13b6. I switched to WLED 0.12 and it ist much, much better...
Does somebody else see this behavior with the different versions? When I switch to a cheap LED-Controller (only the data cable), everything is Ok...

**Comment by alax** [comment]
After switching to a QuinLED Uno, I don't have any more flicker/glitching at all with my UCS2904 LEDs. For reference, I have 275 in one string, spread out over about 150ish linear feet. 

Before, I was using an ESP32 with a 74AHCT125 level shifter, all grounds tied together, and I messed with just about every setting on WLED. Animations would have random pops of color, and my white channel would also randomly activate.

Since it was hand wired/hand soldered, I think the issue here really is related to the quality of the connections between components on the PCB, and the connection to the strip itself. A direct swap for the QuinLED PCB fixed everything straight away.

**Comment by jmerc77** [comment]
getting the flickers flicking me off too. using 0.14.0-b1 compiled for my ESP32-S3. did further experimentation and found the current limiter in led settings to be the problem. if set less than ~30% of the max amperage it starts flickering. I have 288 ws2812b leds connected. its 2 1m strips directly soldered end to end. sig on gpio16 (default). brightness setting of 255.

I did not have the patience to buy a level shifter but found a clever "hack" that gets by with a diode and resistor. apparently, 5v at low-ish current on esp32 outputs does not cook it. so gpio-facing diode with resistor to 5v, tapping between to led sig line worked well. just be sure that its a Schottky diode or something else with fast switching speed due to high frequency sig.

**Comment by jmerc77** [comment]
> 

mine are 144 leds/m. barely used. also tried setting brightness lower instead of lower current limit. no flickering! only flickers when limiting current in settings <30% and only on dim lights during animation. not sure if it will happen on solid color yet though.

**Comment by Hubert97** [comment]
Afrer upgrading from internal linear power supply to external dc/dc converter i started to notice those flashes. Usually in plasma and aurora mode. I am running 680 w2812. I think that this may be caused by bad gnd connection. I' ll make a bypass to led strip and update if that worked or not.

**Comment by sniicker** [comment]
I had extreme glitches. NodeMCU seperatly powered per usb and sk6812 from btf with extra power supply. ~200leds

I could simply fix it by replaceing the usb cable the NodeMCU was powered. No flicker no glitches.
Works perfect.
Give it a try. Mybe you usb cable is shit.

**Comment by jmerc77** [comment]
I'm not using a usb cable for power. my strips are 5v and I am powering BOTH off the same source. this may be the problem though. as far as the circuit of the esp32s3 im using goes, there's a diode between both 5v inputs and the 3.3v regulator. so if the esp is browning out, i may be able to simply add a few hundred microfarads between 3.3v and ground. also my power supply was only 2A and fried during a 24 hour test. getting a 15A supply which will come within 7 days since I have 2m with 288 leds total. also have fuses on the way.

**Comment by cdalexndr** [comment]
Encountered flash glitches with WLED 0.14, downgrading to 0.13 fixes the glitches in my case.
Opened #3751

**Comment by BarrettLowe** [comment]
For me, at least, this was happening because I had multiple segments overlapping. Once I made sure each LED was in one, and only one, segment. The issue went away.

**Comment by mkovero** [comment]
Does it help if you connect GND from power source unit to the esp32 GND?

**Comment by sniicker** [comment]
Connect the input Power of the Amplifier

**Comment by lyrixx** [comment]
Sorry for this lag


@mkovero 
> Does it help if you connect GND from power source unit to the esp32 GND?

No, it's the same :( 

@sniicker 
> Connect the input Power of the Amplifier

I don't understand, Th input power of the Amplifier is already connected 🤔 

![image](https://github.com/user-attachments/assets/17f8e7c2-68c3-4a9a-9d38-dc0302a2beb2)

It's the same issue with the other power input
