### ISSUE TITLE
Hey I want to add an effect to WLED. The original code is from Teknoid303 called „Hyperdrive“ on GitHub.

### ISSUE THREAD

**Issue by GemacFPV** [Aircoookie/WLED#2384]
Where can I add it as a library?

**Comment by fishbone-git** [comment]
https://kno.wled.ge/advanced/custom-features/ for tips on where to edit code. Then create a pull request, rather than fileing a bug.  Good Luck! bonus points if you can write it from a usermod (see also the link provided).
Based on the video, some variant of the meteor effects might already come close

**Comment by GemacFPV** [comment]
I have problems compiling the wled code in the arduino ide, because of missing libraries (f.e. ETH.h) what libraries do I need to compile the unedited code? Can I compile the code ?

**Comment by blazoncek** [comment]
Use Visual Studio Code with PlatformIO.
You can thank me later. 😉
