### ISSUE TITLE
0.12.bin Time setup after reboot not refresh...

### ISSUE THREAD

**Issue by ddijanic** [Aircoookie/WLED#2438]
I made i hwtronics/clock-7seg-fw-WLED  0.12.bin is version.
Its works , I am happy, very happy.

one small issue.

after the power outage, when it turns on again, the time is the year 1970 .1.1 00h: 00m: 00s and it starts counting from that time.
I waited and 1h will not pull myself out of the NTP server

if I enter the wled ui, change the color, the time is set. or run a preset, the time is set, or I turn it off and on via the web and, the time is set...

I tried to make a macro, with 00h and 01 min, run color, run preset, run off, and on .. AND THEY DIDN'T DO THEIR TRICK ...

only if I click on pc or mobile.

IF i go to time, sad disane NTP server, m and enable back on, Noting time is 1970. i only come back if I change color, effect, preset, turn off / on

do you have any ideas?

**Comment by blazoncek** [comment]
Use 0.13

**Comment by ddijanic** [comment]
the clock-7seg-fw-WLED is on 0.12... i am making clock...

**Comment by blazoncek** [comment]
Update to 0.13.

**Comment by ddijanic** [comment]
Give me .bin or link for 0.13 clock 7seg..

**Comment by Aircoookie** [comment]
Make sure your device has an internet connection and can reach the `0.wled.pool.ntp.org` NTP server. You can also ask @dinamitemic to rewrite the 7seg code as a usermod we can compile in using 0.13 :)

**Comment by dinamitemic** [comment]
Hi all, sorry if I do not replied before but I don't have anymore so much free time as before for my projects :(
However, I taken a look at the usermod folder and I've seen two seven segment mods that I think are working as my overlay option.
If someone could test them we can merge everything together and I can update/remove the instruction on my website in order to do not make confusion and standardize the process for using WLED with almost every 7-Seg like clock.
Always happy to see how this project is continously growing!! :D
P.S. Happy new year to all of you!!

**Comment by ddijanic** [comment]
@dinamitemic 
i can test on my watch, no problem.
 just write to me. I use esp6288 4 mb

**Comment by blazoncek** [comment]
For enhancements in usermods, contact usermod developr and have him/her submit updated usermod.
Closing.
