### ISSUE TITLE
WS2815 Stripe with WLED

### ISSUE THREAD

**Issue by ahrens123** [Aircoookie/WLED#2583]
Hi all,

I have a question to the control from the WS2815 stripe.
When I take a look into the datasheet, the data high signal is from 8-12V.
So when I work with an esp controller, a level shifter is necessary.
But here is my problem.
With the levelshifter, I dont get any led signal.
When I use directly the gpio output (3,3V) the leds lights up.
Has anyone an idea?

Thanks.

Best regards

**Comment by Aircoookie** [comment]
Hi,
all WS2815 LEDs to my knowledge accept 5V data signals. The datasheet is confusing here, V<sub>DD</sub> is different from VDD.
V<sub>DD</sub> is typically 12V, VDD is 5V, so the high level is >3.5V. To be in spec, use 5V as the supply voltage for your level shifter and it should work!

Closing since not a WLED issue but feel free to ask for further troubleshooting help here.
