### ISSUE TITLE
Brightness adjustment only lowers brightness in some scenarios

### ISSUE THREAD

**Issue by werkstrom** [Aircoookie/WLED#3031]
### What happened?

After uploading an image via JSON brightness adjustment in peek breaks. I have no devise connected to actual leds at the moment so cannot verify if its only peek or global. The video is pretty self explanatory
 
https://user-images.githubusercontent.com/13434693/212540209-d85fd145-043b-4014-ad88-5890860b6865.mp4

### To Reproduce Bug

1. Download [this](https://github.com/werkstrom/WLED-PixelArtConverter/blob/main/examples/heart%20pixel%20art%2034%20green.png) image and upload to PixelArtConverter ant sent it to the device (16x16 2D setup). 
2. peek
3. adjust brightnes on slider

### Expected Behavior

Should up brightnes to reflect slider

### Install Method

Binary from WLED.me

### What version of WLED?

v0.14.0-b1 "Hoshi" 2301140

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Individual pixel control does not observe/respect global brightness after it has been set.
The global brightness will decrease pixel brightness, but will not increase it. This is by design as individual pixel control is beyond WLED control (one pixel brightness reaches 0 there is no way to increase it to original value).
