### ISSUE TITLE
Power On LED's at Boot - Enhancement or Bug?

### ISSUE THREAD

**Issue by PlasmaSoftUK** [Aircoookie/WLED#3111]
Was unsure whether to file a bug or a feature request for this, it certainly doesn’t work how I expected but thats not to say it isn’t how the developer intended. :wink:

In my WLED Preferences 2 of the options are:

1 - Turn LEDs on after power up/reset
2 - Apply Preset x at boot

Setting option 2 to anything other than 0 seems to override option 1. For example when the thing boots up it defaults to orange LED’s. Thats fine, but I want mine to be green, so I created a green preset and saved it. However if I apply this green preset it also turns the LED’s on. Regardless of what option 1 is set to, this leads to confusion over the 1st option because with it turned off the LED's are still being illuminated.

The issue here is if I don’t apply a preset and have the LED’s not turn on at boot, then ask Alexa to turn on the light, they light up orange and I have to issue a second command to turn them green. If I could apply the preset but not turn them on, when I ask Alexa to turn them on they would turn on and also be green, best of both worlds.

My preferred and expected operation would be that I can set a preset with a brightness BUT NOT have the LED’s turn on. This would be achieved by unticking the box for option 1 but also applying a preset with a brightness. If I wanted them to turn on as well, as per current behaviour I could tick the box for option 1. By having it work in this manner you can apply a preset and choose whether to turn the LED’s on at boot. As it currently works if you set a preset with brightness this overrides the on/off at boot and does what ever the preset is. With a small logic change you could have it work how it does now and also introduce a feature to have the preset applied but not turn them on. No GUI changes are required as the options are already there.

As I say this is the way I expected it to work, maybe there is a reason for it to be like this, but I can’t see it as it offers less flexibility, than if the options where independent.

**Comment by blazoncek** [comment]
I will provide my answer to you form forum here as well for posterity:
"Just create preset with the desired brightness (“include brightness”) and then modify API by replacing "on":true with "on":false. This will apply brightness level but turn LEDs off. If you do not want to modify on state, remove "on" key and value.
You can achieve anything with properly created API commands."

TL:DR This is by design and no change will be provided.

Preset *can* contain any state you want - On or Off included. So, applying a preset at boot will apply its *state* regardless of the "Turn LEDs on at boot" since it is applied *after* on state is enforced from that setting. Still, correct combination of "Turn LEDs on at boot" and JSON API *state* contained within preset will achieve your desired behaviour.
You will need to study JSON API and modify preset using WLED UI.
Hint: Missing state *key:value* pairs are not applied.
