### ISSUE TITLE
Add Pixel Art and non-ASCII characters to Scrolling Text

### ISSUE THREAD

**Issue by jaredvacanti** [Aircoookie/WLED#3127]
**Is your feature request related to a problem? Please describe.**

I would like to scroll images (pixel art) and unicode characters in the Scrolling Text effects. And a second issue that could be solved by this issue is I would eventually like to use more than 32 characters in Scrolling Text.

**Describe the solution you'd like**
The problem can probably be solved a few different ways. Maybe there are some library restrictions.

An ideal one would be to map the pixels in an `m`x`n` drawing matrix to an `m`x`l` segment, and scroll it if `n` > `l` (the behavior that text scrolling has now). Then you could draw images, or draw your own text, before scrolling the section. This solution would enable some features, too.

**Describe alternatives you've considered**
The JSON API allows for individually addressable pixels, so pixel art can be put into segments already. I can move a pixel over manually with the API, but not to translate or scroll the whole "scene".

**Additional context**

Some other issues could also be addressed with this method:

- https://github.com/Aircoookie/WLED/issues/3020
- https://github.com/Aircoookie/WLED/issues/3071

e.g. custom fonts and spacings would be "drawn" into a scene box and that scene box would translate or scroll on the screen. This could also allow for wipe transitions between two larger scenes. Also, if segments can be grouped and scrolled together, that could get around the 32 character limit.

Thanks for all of your work on this, it's a great project :)

**Comment by blazoncek** [comment]
Hi. Thanks for the suggestion.
As you may have read in the issues you mentioned, adding unicode characters is infeasible as it would require extensive flash and RAM requirements so it will not be implemented unfortunately.
As for *scrolling* or *shifting/rotating* pixel art images the problem lies in stateless LED output used in that case (API command `"i"`). Once the image is sent to WLED as a series of "i" pixels, WLED `forgets` what was drawn and has no proper way of shifting such state.
So, unfortunately, both features cannot be implemented in the current form.

But (there is always but) if someone writes a usermod for custom effect which will draw pixel art images it can also implement animated images and/or scrolling images.

**Comment by Travisc1337** [comment]
Not sure if it will help. But I ended up using xlights and added the wled as a controller. Mostly added a matrix and added an affect on it, more just playing around with it, but I will say it works great, you can have the pixel art moving in all kinds of ways. but for it to work, you would have to have xlights running on a system for it to do anything on the matrix. Not sure if there is a way to export the script that xlights is using and code it for the api side.

**Comment by werkstrom** [comment]
Any external device, able to send CURL at some sort of interval/schedule would do the trick if you can live with it not being stand alone on the WLED device. I haven't tried, but you should probably be able to do it from bat/PowerShell/chron and the likes. Pixel Art Creator should create the CURL for you (if it doesn't, let me know so we can fix it :) ).
