### ISSUE TITLE
Preset not saving 50x48 matrix after loaded using JSON 

### ISSUE THREAD

**Issue by KevinGroninga** [Aircoookie/WLED#3160]
### What happened?

I have a 50x48 matrix driven by a Dig-Quad and an ESP32 running the 0.14.0-b2 version of audio reactive WLED.  I recently discovered a tool for creating pixel art and uploading to the board using JSON.  Before uploading the JSON, I set the effect to Solid and black as the color.  I then send the JSON and my matrix will display that image.   However, if I go to Presets and create a NEW Preset, it doesn’t save the displayed image. It only saves the effect and color I originally set, the solid black.  

### To Reproduce Bug

Load a matrix using pixel art JSON and then create a new Preset.

### Expected Behavior

Shouldn’t the current displayed pixel/color be saved?

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-b2 audio reactive 

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
There is a limit of how big a pixel art JSON can be. Unfortunately that is way less than 2400 pixels you are using so it gets split into "chunks".
You can try to compile WLED yourself and increase JSON buffer (from 24k to 48k or more) but be vary that it may cause WLED instability.

However this will still not allow you to save currently displayed pixel art. The information abut displayed image is lost immediately upon displaying it and there is no way for WLED to retrieve it. If you want to save a preset with the image you will need to save API call from pixel art creator. But since it is split into chunks...

BTW Official version will not have bigger JSON buffer until it is thoroughly tested and confirmed working without issues.
