### ISSUE TITLE
athom music controller remote

### ISSUE THREAD

**Issue by lesleylemmens** [Aircoookie/WLED#3172]
Since i updated my athom music controller to 0.14.0.b1 i can no longer use the remote of my controller.
I have seen somewere there is a config for this remote in a newer beta? I do not understand this, but also the sound reactive buttons will not work.
If i choose a standard 24 key remote then fuctions do not match the keys.
Does anyone have a json file for this remote? Is there a way to make all button work?
![athom remote](https://user-images.githubusercontent.com/128682809/231559095-e5915572-1cec-44c4-9603-e07e9419a674.png)

**Comment by softhack007** [comment]
Hi, 
Please next time use discord for questions and support questions (links below).

The athom controller is compatible with WLED, however it has a remote and microphone that are not fully supported in standard WLED. The truth is, athom basically grabbed a copy of our source code, added their own IR, then sold the hardware+firmware package as their own product. We did not even receive a "thank you" from them.

<br/>


That said, you could be lucky because one of our devs recently "put his hand" on this controller and managed to get it going. In the [MoonModules fork](https://github.com/MoonModules/WLED), you can find a [special firmware build for athom](https://github.com/MoonModules/WLED/releases/download/v0.14.0.b15/WLEDMM_0.14.0-b15.21_athom_music_esp32_4MB_M.bin) esp32 hardware.


<a href="https://discord.gg/4CQRmfR"><img src="https://discordapp.com/api/guilds/700041398778331156/widget.png?style=banner2" width="30%"  align="middle"></a>
Join Discord to discuss the [sound reactive fork(s)](https://discord.gg/4CQRmfR) of WLED. 

<a href="https://discord.gg/KuqP7NE"><img src="https://discordapp.com/api/guilds/473448917040758787/widget.png?style=banner2" width="30%" align="middle"></a>
Join Discord to discuss [AirCookie's WLED](https://discord.gg/KuqP7NE).

**Comment by lesleylemmens** [comment]
Thank you, i will have to figure out how to use discord. 
I already found that special firmware. It works. Only the audio reactive buttons have different function.
Sorry i did not know the athom version was not officialy supported.

**Comment by softhack007** [comment]
Below a picture showing how @ewoudwijma configured his IR remote in the code.
If you want another layout, its probably best to look into making [your own IR.JSON](https://kno.wled.ge/interfaces/json-ir/json_infrared/). 

![226985327-1539c123-5040-438f-a88d-ef4ca82251ba jpeg](https://user-images.githubusercontent.com/91616163/232230817-28a981c5-ab5c-4792-9158-4f74b7053b64.jpg)


IR codes are listed here:

https://github.com/MoonModules/WLED/blob/244a6137d23f0795af3c9809b28171a2c5e194b4/wled00/ir_codes.h#L215-L240

**Comment by softhack007** [comment]
Closing, as its not planned to explicitly add more remotes into our source code. Custom IR.JSON can be used to configure all IR buttons as you like.

**Comment by xkvmoto** [comment]
Attached is the ir.json file I use for the Athom Addressable Strip Controller  (use JSON Remote option in LED Preferences)
[ir.json](https://github.com/Aircoookie/WLED/files/13199036/ir.json)

**Comment by softhack007** [comment]
> Attached is the ir.json file I use for the Athom ir Remote for the Addressable Strip Controller (use JSON Remote option in LED Preferences) [ir.json](https://github.com/Aircoookie/WLED/files/13199036/ir.json)

@xkvmoto would you mind to make a PR, to add your IR.json into our IR JSON collection? 

https://github.com/Aircoookie/WLED/tree/main/usermods/JSON_IR_remote

**Comment by LutraVulgaris** [comment]
go to https://github.com/athom-tech/Sound-Reactive-WLED/releases/tag/0.13.3 and download https://github.com/athom-tech/Sound-Reactive-WLED/releases/download/0.13.3/Athom_soundReactive.bin

install it OTA (enter default password (wledota) and enable OTA updates

now you have the correct firmware again on your athom wled, with the use of the remote (enable the correct 24 key remote with music in the LED preference settings)
