### ISSUE TITLE
Enabling MQTT in WLED 0.14.0 resets every couple minutes

### ISSUE THREAD

**Issue by YvesLev** [Aircoookie/WLED#3435]
### What happened?

Installed latest version of WLED 0.14.0-b6 (Tried AR and non AR) from web installer on a ESP32 Dev board (ESP32-WROOM-32D)
(Also tried on another ESP32 dev board (32D) and also on a ESP32 mini board).

Was working great until I enable MQTT using my Mosquito server IP.  (User/Pass empty as I use mosquito anonymously).

With MQTT Enabled, MQTT seemed to work fine for not very long. (Using MQTT Explorer to monitor).
Then, no msg were sent from WLED and after few minutes (1-2), WLED resets itself (Back to default preset)...

It keeps doing this in a loop.

### To Reproduce Bug

1- Install WLED 0.14.0-b6 on a ESP32 board.
2- Make a preset with ColorTwinkle effect for example.  Leave default preset to 0 (Solid).
3- Enable MQTT (No user/pass, anonymous)
4- After reboot of WLED, choose Preset 1.

### Expected Behavior

1- After about 2 minutes (could be from 1 to 5 minutes), it should reset by itself and revert back to preset 0 (Solid).
2- Will keep doing this indefinitely.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-b6 Build 2310010

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
[11:44:53]---DEBUG INFO---
[11:44:53]Runtime: 180082
[11:44:53]Unix time: 1696866294,082
[11:44:53]Free heap: 201312
[11:44:53]Wifi state: 3
[11:44:53]State time: 0
[11:44:53]NTP last sync: 999000000
[11:44:53]Client IP: 192.168.2.62
[11:44:53]Loops/sec: 2050
[11:44:53]Loop time[ms]: 2/4
[11:44:53]UM time[ms]: 0/1
[11:44:53]Strip time[ms]: 0/2
[11:44:53]Segments: 1 -> 86B
[11:44:53]Modes: 4*187=748B
[11:44:53]Data: 4*187=748B
[11:44:53]Map: 2*0=0B
[11:44:53]Buffer: 3*144=432B
[11:44:56]Reconnecting MQTT
[11:44:56]Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
[11:44:56]Core 0 register dump:
[11:44:56]PC      : 0x4011ff0b  PS      : 0x00060630  A0      : 0x801200c3  A1      : 0x3ffb5f50  
[11:44:56]A2      : 0x00000000  A3      : 0x3ffdd620  A4      : 0x00000000  A5      : 0x3ffdd41e  
[11:44:56]A6      : 0x00000014  A7      : 0x3ffb5500  A8      : 0x80085530  A9      : 0x3ffb5f30  
[11:44:56]A10     : 0x3ffd7f90  A11     : 0x0000166f  A12     : 0xf28e6cde  A13     : 0x00000b38  
[11:44:56]A14     : 0x00000020  A15     : 0x00000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
[11:44:56]EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  
[11:44:56]
[11:44:56]ELF file SHA256: 0000000000000000
[11:44:56]
[11:44:56]Backtrace: 0x4011ff08:0x3ffb5f50 0x401200c0:0x3ffb5f70 0x40120104:0x3ffb5f90 0x40156145:0x3ffb5fc0 0x4015c30f:0x3ffb5fe0 0x40160ad2:0x3ffb6010 0x4014b023:0x3ffb6030 0x4008b5d2:0x3ffb6060
[11:44:56]
[11:44:56]Rebooting...
[11:44:56]ets Jul 29 2019 12:21:46
[11:44:56]
[11:44:56]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[11:44:56]configsip: 0, SPIWP:0xee
[11:44:56]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[11:44:56]mode:DOUT, clock div:2
[11:44:56]load:0x3fff0030,len:1184
[11:44:56]load:0x40078000,len:13132
[11:44:56]load:0x40080400,len:3036
[11:44:56]entry 0x400805e4
[11:44:57]
[11:44:57]---WLED 0.14.0-b6 2310010 INIT---
[11:44:57]esp32 v3.3.6-16-gcc5440f6a2
[11:44:57]arduino-esp32 v1.0.x
[11:44:57]
[11:44:57]CPU:   ESP32-D0WDQ5 rev.3, 2 core(s), 240MHz.
[11:44:57]FLASH: 4MB, Mode 3 (DOUT), speed 40MHz.
[11:44:57]heap 292388
[11:44:57]PIN ALLOC: Pin 1 successfully allocated by 0x89 (137)
[11:44:57]Registering usermods ...
[11:44:57]heap 292388
[11:44:57]Reading config
[11:44:57]Reading settings from /wsec.json...
[11:44:57]JSON buffer locked. (3)
[11:44:57]JSON buffer released. (3)
[11:44:57]JSON buffer locked. (1)
[11:44:57]Reading settings from /cfg.json...
[11:44:57]Removing all.
[11:44:57]PIN ALLOC: Pin 26 successfully allocated by 0x82 (130)
[11:44:57]Successfully inited strip 0 (len 144) with type 22 and pins 26,186 (itype 21)
[11:44:57]PIN ALLOC: Pin 0 successfully allocated by 0x85 (133)
[11:44:57]Starting usermod config.
[11:44:57]JSON buffer released. (1)
[11:44:57]Initializing strip
[11:44:57]Loading custom palettes
[11:44:57]Loading custom ledmaps
[11:44:57]heap 287932
[11:44:57]Usermods setup
[11:44:57]heap 287932
[11:44:57]initServer
[11:44:57]heap 283928
[11:44:57]lastReconnectAttempt == 0
[11:44:57]Access point disabled (init).
[11:44:57]Connecting to PuttPutt...
[11:44:57]Loop took 128ms.
[11:44:57]Usermods took 0ms.
[11:44:57]Strip took 2ms.
[11:45:00]Loop took 718ms.
[11:45:00]Usermods took 0ms.
[11:45:00]Strip took 1ms.
[11:45:00]
[11:45:00]Connected! IP address: 192.168.2.62
[11:45:00]Init STA interfaces
[11:45:00]mDNS started
[11:45:00]Reconnecting MQTT
[11:45:00]Reconnecting MQTT
[11:45:00]Loop took 35ms.
[11:45:00]Usermods took 0ms.
[11:45:00]Strip took 0ms.
[11:45:00]MQTT ready
[11:45:00]Publish MQTT
[11:45:00]MQTT ready
[11:45:00]Publish MQTT
[11:45:16]WS client connected.
[11:45:16]JSON buffer locked. (12)
```

### Anything else?

I'm using an ASUS Router RT-AC68U with ASUSWRT-MERLIN

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
As there were no changes in MQTT in several months and it appears that MQTT is working on my installs I would suspect something odd in your configuration (broker or client) or messages destined for WLED device.
Please capture MQTT packets (using Wireshark, MQTT Explorer or something similar) and post the message which is followed by a crash.

It would also be very helpful if you can use PIO to build & flash your ESP and then use exception decoder to disassemble backtrace.

**Comment by YvesLev** [comment]
Thank you very much for your help.

I'm still newbie in this coding, pio things.
What you ask, wireshark, pio exception decoder thing is a challenge for me but I'm might look at that eventually.

I thought maybe the problem could come from the fact I use MQTT anonymous without any user/pass, which, I believe, is not that common these days.

I've been using Mosquito broker windows service since 2018-19 and I use HA, Tasmota, Z2M, esphome, etc all using MQTT for all that time.  I doubt my mqtt config is the culprit but who knows.

I'm going to ask a friend to try WLED on an ESP32 wiht MQTT enabled. He has the MQTT HA Addon installed with user/pass.

Also I will try to flash older version of WLED...

Thanks again.

**Comment by blazoncek** [comment]
I am not using authenticated MQTT myself. I also use Mosquitto, though it is hosted on Linux machine.
As I said most likely cause may be particular message received.

Wireshark and MQTT explorer are simple tools with plenty of tutorial videos on-line so it should not be too difficult to obtain packets from them.

**Comment by blazoncek** [comment]
Please provide MQTT packets destined for WLED.

**Comment by YvesLev** [comment]
When I figure out how to achieve that, I'll post it.

**Comment by blazoncek** [comment]
MQTT explorer or Mosquitto client.

**Comment by YvesLev** [comment]
I have and use MQTT Explorer.
There are not much msg from/to WLED since it appears WLED sends publish only on changes.
(And I just leave WLED running as his without making changes).
And there are no msg sent to WLED for now.

So I'm not sure what you need here.

If I change the brightness, with b6, sometime I'll see the change in MQTT, sometime not.
When I stop seeing WLED changes in MQTT explorer, it is not very long that it resets itself.
Sometime after reset, changes to brightness, status will start to appear again in MQTT explorer, sometime not...

But if I do not touch WLED, there is nothing to see in MQTT explorer and wled will still self reset every couple of minutes.

**Comment by blazoncek** [comment]
I cannot reproduce, sorry.
![Screenshot 2023-10-10 at 19 27 29](https://github.com/Aircoookie/WLED/assets/7722392/d0c0a839-139f-4f16-bfd9-5bf74ad9878a)

**Comment by YvesLev** [comment]
![image](https://github.com/Aircoookie/WLED/assets/37024905/548499b7-9816-4b29-bc29-fb3277d27050)

![image](https://github.com/Aircoookie/WLED/assets/37024905/30b0672a-1b38-43c3-bead-dd75a05a17e0)

**Comment by YvesLev** [comment]
My MQTT config in WLED for information.

![image](https://github.com/Aircoookie/WLED/assets/37024905/0a0e4502-ce33-48e3-bcef-c1dc91070761)

**Comment by blazoncek** [comment]
The only thing I can now think of is some sort of low-level problem with your MQTT set up (not WLED as that looks correct).
![Screenshot 2023-10-10 at 22 48 13](https://github.com/Aircoookie/WLED/assets/7722392/b84a985c-56d7-48cf-8a33-83beb361aa6f)
I added two more devices and left the MQTT Explorer run for 3 hours. All going strong no reboot or missing messages.

**Comment by YvesLev** [comment]
Juste tested 0.14.0-b6 with a D1 mini 8266 and MQTT has been working flawlessly for 30 min now.

So for me up to now:
0.13.3 Release: MQTT is working for ESP32.
0.14.0-b6: MQTT is not working properly for ESP32 (Tried with 3 different) (It works sometime but self reset every couple of minutes)
0.14.0-b6: MQTT is working with ESP8266.

**Comment by YvesLev** [comment]
My Mosquitto broker (Windows service) was 2.0.14 and I just upgraded to the latest 2.0.18.

Now the ESP32 with wled b6 and MQTT enabled seems to hold with no self resets for over 10 minutes now...
I let it run overnight and post tomorrow.

Thank you for your help and patience.

**Comment by blazoncek** [comment]
Please close the issue then.

**Comment by YvesLev** [comment]
I'm going to re-open this issue even if it appears I'm the only one having this problem.

So after updating my Mosquito broker, I thought it solved the problem but the day after, I tried the latest WLED on an ESP32 and the self resetting problem was there.

So I guess the rebooting of my NUC, hosting the Mosquitto Service and also the HA Virtualbox, corrected the problem just for a little while...

Actually, when the self resetting seems to be gone, if I cycle power to the esp, the problem comes back.  I don't need to wait long after a reboot of the NUC.  (I even wonder if the reboot is related)

As I said earlier, the same ESP32 with a previous release (0.13.x) and MQTT enabled is working perfectly fine.

I will still do some tests and report back.

**Comment by YvesLev** [comment]
I compiled the 0.14.0 source with Debug option.
Upload and monitor...

`Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4015ae93  PS      : 0x00060830  A0      : 0x8015af87  A1      : 0x3ffb5bd0  
A2      : 0x00000000  A3      : 0x3ffdd0b4  A4      : 0x00000000  A5      : 0x00000001
A6      : 0x00060021  A7      : 0x00000000  A8      : 0x80085730  A9      : 0x3ffb5bb0  
A10     : 0x3ffdd900  A11     : 0x0000165b  A12     : 0x9735dff4  A13     : 0x00000b38
A14     : 0x00000020  A15     : 0x00000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff

ELF file SHA256: 0000000000000000

Backtrace: 0x4015ae90:0x3ffb5bd0 0x4015af84:0x3ffb5bf0 0x4015afce:0x3ffb5c10 0x40195285:0x3ffb5c40 0x4019b44f:0x3ffb5c60 0x4019fc12:0x3ffb5c90 0x4018a0eb:0x3ffb5cb0 0x4008b7e6:0x3ffb5ce0
  #0  0x4015ae90:0x3ffb5bd0 in AsyncClient::_lwip_fin(tcp_pcb*, signed char) at .pio\libdeps\WLED_ESP32_BH1750\AsyncTCP\src/AsyncTCP.cpp:1153
  #1  0x4015af84:0x3ffb5bf0 in AsyncClient::_s_lwip_fin(void*, tcp_pcb*, signed char) at .pio\libdeps\WLED_ESP32_BH1750\AsyncTCP\src/AsyncTCP.cpp:1153
  #2  0x4015afce:0x3ffb5c10 in _tcp_recv(void*, tcp_pcb*, pbuf*, signed char) at .pio\libdeps\WLED_ESP32_BH1750\AsyncTCP\src/AsyncTCP.cpp:1153
  #3  0x40195285:0x3ffb5c40 in tcp_input at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/core/tcp_in.c:475 (discriminator 1)
  #4  0x4019b44f:0x3ffb5c60 in ip4_input at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/core/ipv4/ip4.c:750
  #5  0x4019fc12:0x3ffb5c90 in ethernet_input at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/netif/ethernet.c:184
  #6  0x4018a0eb:0x3ffb5cb0 in tcpip_thread at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/api/tcpip.c:483
  #7  0x4008b7e6:0x3ffb5ce0 in vPortTaskWrapper at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DOUT, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1084
load:0x40078000,len:11220
load:0x40080400,len:5360
entry 0x4008067c`

**Comment by blazoncek** [comment]
Unfortunately backtrace shows no WLED code.
You will need to open an issue with library provider (AsyncTCP).

**Comment by YvesLev** [comment]
I tried to tweak a bit my wifi config in the router after reading some tips...
But it didn't solve the problem with WLED when MQTT is enabled...

So I deactivated Mosquito windows service and setup the Mosquito addon in Home Assistant.
(Had to reconfigure all my devices but it's ok...)

Up to now, the problem seems gone...  Very strange...

**Comment by hajeth** [comment]
Hopefully I can reactivate this issue, because Im facing the same problem.

Hardware: ESP32 WROOM-32
WLED Version: v0.14.2-b1
MQTT Broker Mosquitto 2.0.18 running on Windows Server 2019

When MQTT is enabled, after some minutes the ESP32 reboots.

Debug log (with AsyncTCP debug output activated, too) shows:

> event arg == NULL: 0x3ffdfcac
event arg == NULL: 0x3ffdfcac
event arg == NULL: 0x3ffdfcac
event arg == NULL: 0x3ffdfcac
Reconnecting MQTT
C: 0x3ffdcbe4 0x3ffdcec8 0
+F: 0x3ffdfcac
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4012088b  PS      : 0x00060230  A0      : 0x80120a43  A1      : 0x3ffb5ce0
A2      : 0x00000000  A3      : 0x3ffdfcac  A4      : 0x00000000  A5      : 0x00000063  
A6      : 0x00000000  A7      : 0x3ffb5c49  A8      : 0x00000000  A9      : 0x3ffb5c50
A10     : 0x0000000a  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00001800  
A14     : 0x3ffb5c47  A15     : 0x3ffb5280  SAR     : 0x00000005  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  
ELF file SHA256: 0000000000000000
Backtrace: 0x40120888:0x3ffb5ce0 0x40120a40:0x3ffb5d00 0x40120a9e:0x3ffb5d20 0x40156fe9:0x3ffb5d50 0x4015d26f:0x3ffb5d70 0x40161c1a:0x3ffb5da0 0x4014be2b:0x3ffb5dc0 0x4008b936:0x3ffb5df0
  #0  0x40120888:0x3ffb5ce0 in AsyncClient::_lwip_fin(tcp_pcb*, signed char) at .pio\libdeps\esp32dev\AsyncTCP\src/AsyncTCP.cpp:1153
  #1  0x40120a40:0x3ffb5d00 in AsyncClient::_s_lwip_fin(void*, tcp_pcb*, signed char) at .pio\libdeps\esp32dev\AsyncTCP\src/AsyncTCP.cpp:1153
  #2  0x40120a9e:0x3ffb5d20 in _tcp_recv(void*, tcp_pcb*, pbuf*, signed char) at .pio\libdeps\esp32dev\AsyncTCP\src/AsyncTCP.cpp:1153
  #3  0x40156fe9:0x3ffb5d50 in tcp_input at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/core/tcp_in.c:475 (discriminator 1)
  #4  0x4015d26f:0x3ffb5d70 in ip4_input at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/core/ipv4/ip4.c:750
  #5  0x40161c1a:0x3ffb5da0 in ethernet_input at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/netif/ethernet.c:184
  #6  0x4014be2b:0x3ffb5dc0 in tcpip_thread at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/api/tcpip.c:483
  #7  0x4008b936:0x3ffb5df0 in vPortTaskWrapper at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
.
Rebooting...
ets Jul 29 2019 12:21:46
.
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DOUT, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1084
load:0x40078000,len:11220
load:0x40080400,len:5360
entry 0x4008067c

I am aware that the exception occurs in AsyncTCP and will also try to contact the programmer regarding this issue.


But every time the reboot occurs there is a "Reconnect MQTT" Message before the crash and i am wondering why WLED issues MQTT reconnects, when already connected. Also it seems it does 2 connection attempts (The Mosquitto log shows incoming connections from two TCP Ports to Port 1883

Mosquitto Log:

> 1708761740: New connection from 192.168.17.28:56454 on port 1883.
1708761740: New connection from 192.168.17.28:56455 on port 1883.
1708761740: Client WZ_WLED_TV already connected, closing old connection.
1708761740: New client connected from 192.168.17.28:56454 as WZ_WLED_TV (p2, c1, k60).
1708761740: Will message specified (7 bytes) (r1, q0).
1708761740: 	wled/WZ_WLED_TV/status
1708761740: Sending CONNACK to WZ_WLED_TV (0, 0)

The packet trace shows a successful MQTT connection (Packet No 75), then the ESP32 is not available anymore due the reboot 

![LastPacket](https://github.com/Aircoookie/WLED/assets/161116591/cefb4c3c-a923-4712-8907-850715156b5d)

Full Logs, and packet trace attached

Many thanks for any help to solve this tricky one

[Attachments.zip](https://github.com/Aircoookie/WLED/files/14392237/Attachments.zip)

**Comment by blazoncek** [comment]
MQTT reconnect only happens when library detects disconnect from MQTT broker. There is nothing fancy in WLED.

``c++
...
  if (mqtt == nullptr) {
    mqtt = new AsyncMqttClient();
    mqtt->onMessage(onMqttMessage);
    mqtt->onConnect(onMqttConnect);
  }
  if (mqtt->connected()) return true;

  DEBUG_PRINTLN(F("Reconnecting MQTT"));
...
```

I know it may sound corny but please try another broker. It happened many times in the past that Windows versions of Mosquitto caused WLED reset.

**Comment by hajeth** [comment]
Many thanks for your reply. As I wrote, I also tried with bevywise mqtt broker with same result.

Regards, Thomas
________________________________

**Comment by booherbg** [comment]
Hi there, I'm having the same experience with 14.3, and 15.0. I can try a different broker, but mosquito has been working wonderfully for my needs.

**Comment by hajeth** [comment]
On my side I removed the windows mosquito broker and switched to the mosquito broker on my HomeAssistant box. The problem seems to be related to the AsyncTCP library used by WLED, but I never got a response from the provider. Did not try very hard, because changing the broker solved it here.

**Comment by booherbg** [comment]
Just a quick update - I switched from mosquitto to EMQX on my raspberry pi and haven't experienced any issues in my limited testing. Very strange.
