### ISSUE TITLE
v0.14.1-b2: ESP8266 fade issue with Breathe effect on Solid and the freeze function

### ISSUE THREAD

**Issue by casesolved-co-uk** [Aircoookie/WLED#3643]
### What happened?

See video for the interaction between the Breathe Effect and Solid:

https://github.com/Aircoookie/WLED/assets/110036763/eb1e9b9d-018e-475a-ae0c-8d7ba2b99dce

### To Reproduce Bug

Follow the video

### Expected Behavior

Solid remains solid, freeze freezes the segment and prevents changes

### Install Method

Binary from WLED.me

### What version of WLED?

v0.14.1-b2

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by casesolved-co-uk** [comment]
Related:
https://github.com/Aircoookie/WLED/pull/3631

**Comment by blazoncek** [comment]
Please power your strip from a separate power supply. 1m strip with 144 LEDs/m requires 8A of current at full brightness.
There are no "interference" between segments code wise.

**Comment by dosipod** [comment]
I see the same behavior when using two segments on 16x16 matrix , I do not thing this is HW related

**Comment by blazoncek** [comment]
> I see the same behavior when using two segments on 16x16 matrix , I do not thing this is HW related

Please post your configuration and picture of HW set up. As mentioned above there are no interactions between different segments (apart from ABL) to do that.
ABL stands for Automatic Brightness Limiter. Turn it off and then compare.

**Comment by dosipod** [comment]
I was actually testing with a remote unit using ddp but sure if you disable limiter  the issue is no longer there

**Comment by softhack007** [comment]
Makes sense to explain the behaviour with ABL (auto  brightness limiter).
* segment1 is solid and power usage is close to ABL limit
* segment2 turns on, LEDs draw extra power
* ABL tries to bring power usage back into the limit, by reducing global brightness temporarily.

--> segment1 seems to fade or flicker.

This would be expected behaviour. 

@casesolved-co-uk please try this:
* verify that your cables are thick enough for 5-8Amp current
* reduce global brightness to 50% or less
* disable auto brightness limiter in LED settings
* check if the fading / flickering is still there (should be gone now)
* keep an eye on your cables, go ensure they don't heat up.

**Comment by casesolved-co-uk** [comment]
@softhack007 thanks for the explanation, ABL explains the effect interaction and goes away with ABL disabled.

It cannot be a current issue in this case as the power is being fed directly to the board where the 3 LEDs are fading out. Plus the behaviour is clearly software controlled.

Current is 0.7A with ABL enabled and rises to 1.4A with it disabled, including 0.2A for the board.

And the freeze issue goes away too.

Since we're on the subject, does ABL only apply to onboard busses and is ignored for external busses, e.g. on the network?

**Comment by blazoncek** [comment]
Yes.
