### ISSUE TITLE
Increase FX speed?

### ISSUE THREAD

**Issue by StormPie** [Aircoookie/WLED#39]
Hey!

Version 0.7.1 😃😃😃!

I have recently acquired a 1M 144 LED strip, for more LED madness. WLED looks absolutely awesome on it! However, now that i've got such a high density strip, it seems the effects could be that little bit faster to make high speed effects look super cool on HD strips, and even faster on less dense strips.

Is this possible?

Thanks heaps

**Comment by Aircoookie** [comment]
Hey,

of course, I should add such an option! On a 60 LED/m strip many animations will be 2x slower and on 144 LED/m even 5x slower! In version 0.8.0 I will add these super-cool FastLED noise effects. Then i can also add a setting where you select your strip density, so it adjusts the timings so that the effect will run the same speed on a 30 and 144 strip of the same length :)

**Comment by StormPie** [comment]
Heck yeah! Super keen for the update 😄

**Comment by Luke-Beck** [comment]
I'd really like for this to be considered again please

**Comment by czweb** [comment]
I hope that the maximum speed can be greater than 255, or there is a speed multiplier that can be adjusted

**Comment by blazoncek** [comment]
> I hope that the maximum speed can be greater than 255, or there is a speed multiplier that can be adjusted

It will not.
Name effects that need speeding up and we'll see what we can do.
