### ISSUE TITLE
WLED from HA on Dig2Go controller stops it from working

### ISSUE THREAD

**Issue by pfurrie** [Aircoookie/WLED#4095]
### What happened?

HA detected WLED 14.2 on Dig2Go controller.  After installing this to any controllers, they stop working (stop lighting attached lights).

### To Reproduce Bug

1. Setup Dig2Go controller, using WLED firmware from this page:
https://install.quinled.info/dig2go/
2. Add Dig2Go to HA.
3. When HA suggests update for the Dig2Go controller, install the firmware as advised (which takes firmware from 14.2 to 14.4).
4. After install Dig2Go can't light any LEDs.  Function to power lights is broken.

### Expected Behavior

When update is installed, Dig2Go device continues to operate properly (can light LEDs).

### Install Method

Binary from WLED.me

### What version of WLED?

14.4

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

This happened to two controllers.  Thought they were broken, but after several hours, someone suggested reflashing with the QuinLED WLED installer webpage.  This worked first time.  Afterwards, I let HA update the Dig2Go, but then immediately lost ability to light LEDs again.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
> someone suggested reflashing with the QuinLED WLED installer webpage. This worked first time. Afterwards, I let HA update the Dig2Go, but then immediately lost ability to light LEDs again.

If you have a custom firmware, it's not a good idea to let HA pick and install a firmware update for you. It's because HA does not know about special build flags that might be needed for your controller, so it simply picks a standard build.

Please look here for firmware updates that are configured to match your controller, and install directly in WLED without relying on HA.

https://github.com/filipvdb/QuinLED-Firmware
