### ISSUE TITLE
sketch (108%) of program storage space

### ISSUE THREAD

**Issue by pete111** [Aircoookie/WLED#41]
Hi @Aircoookie 
I am trying to burn version 0.7.1 to my esp8266-01 but I am getting this error:
Sketch uses 469491 bytes (108%) of program storage space. Maximum is 434160 bytes.
Global variables use 52292 bytes (63%) of dynamic memory, leaving 29628 bytes for local variables. Maximum is 81920 bytes.

With 0.6.5 version I did not have this problem. 
Any idea please?

**Comment by Aircoookie** [comment]
Hi Pete,

in 0.7.0 I added the mobile UI page, which has a size of a few kilobytes. With that addition, the WLED program no longer fits on ESP8266-01 with so little as 512K flash. You can however disable the mobile UI and use the 01 by un-commenting the '''#define WLED_FLASH_512K_MODE''' in wled00.ino . However, I'd suggest upgrading to Wemos D1 or similar, because the OTA software update via WiFi also probably doesn't work with less than 1MB flash.

Hope I could help you!
