### ISSUE TITLE
Apple Remote Codes not working with IR JSON  

### ISSUE THREAD

**Issue by jay-b** [Aircoookie/WLED#4196]
### What happened?

I'm trying to get an Apple remote (older white variant) connected to a ESP32 with a connected KY-022. Have got the codes via an Arduino sketch and created a JSON file similar to the Apple Remote v2 file from the documentation

<img width="1312" alt="Screenshot 2024-10-16 at 23 07 01" src="https://github.com/user-attachments/assets/78c5d6bb-4159-46a6-b456-8a4a56ad6ae8">

![SACCAPPA1156A_l-1261355943](https://github.com/user-attachments/assets/e5a357c4-d309-445a-a8cc-0d05300dbe2c)

```
{  
  "0xF40587EE": { "label": "play","cmnt": "Play/Pause", "cmd": {"ps":"1~9~r"} },
  "0xF40387EE": { "label": "menu", "cmnt": "On/Off", "cmd": {"on":"t"} },
  "0xF40C87EE": { "label": "down", "cmnt": "Brightness -", "cmd": {"bri":"~-8"} },
  "0xF40A87EE": { "label": "up", "cmnt": "Brightness +", "cmd": {"bri":"~+8"} },
  "0xF40987EE": { "label": "left", "cmnt": "Effect -", "cmd": {"seg":{"fx":"~-"}} },
  "0xF40687EE": { "label": "right", "cmnt": "Effect +", "cmd": {"seg":{"fx":"~+"}} }
}
```

I've tested using these pins: 15, 13, 4. Also, to check there isn't an issue with my file system storing the JSON file I've tested using the 24 button JSON code from the documentation which works fine when using one of those remotes. I also tried changing one of the HEX codes in that file with one from my Apple remote and that didn't work when using the Apple remote.

### To Reproduce Bug

If you have access to one of these older Apple remotes, retrieve the HEX codes, upload the JSON to a WLED installation.

### Expected Behavior

The remote should execute the JSON.

### Install Method

Binary from WLED.me

### What version of WLED?

0.15.0-b5

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
Does it work if you use the codes you get from WLED over Serial output?

**Comment by blazoncek** [comment]
As @DedeHai mentioned, use WLED to display IR codes, not Arduino sketch.

**Comment by jay-b** [comment]
> Does it work if you use the codes you get from WLED over Serial output?

Thanks, how do I do that?

**Comment by DedeHai** [comment]
connect it to USB, monitor serial, press IR keys.

**Comment by jay-b** [comment]
I have the ESP32 connected via USB but see no options in the WLED settings for monitoring the serial? Sorry, very new to this project and inexperienced when it comes to Arduino stuff.

**Comment by jay-b** [comment]
Managed to get the correct codes from the serial monitor in Arduino, so it's all working!

**Comment by DedeHai** [comment]
for future reference: the serial output of IR codes is always active, just open the serial port with 115200 baud rate and press IR keys. If your hardware is correct, the received codes will be written to serial.

**Comment by easaw** [comment]
My Apple Remote v1 output slightly different data for a double tap.

I assume the codes are different per remote, but here's what I've done:

```
{
  "desc": "Apple Remote v1 - Presets",
  "0x77E12047": { "label": "play","cmnt": "On/Off", "cmd": {"on":"t"} },
  "0xB8144E4B": { "label": "play","cmnt": "On/Off", "cmd": {"on":"t"} },
  "0x77E14047": { "label": "menu", "cmnt": "On/Off", "cmd": {"on":"t"} },
  "0xA72A9664": { "label": "menu", "cmnt": "On/Off", "cmd": {"on":"t"} },
  "0x77E1D047": { "label": "up", "cmnt": "Brightness +", "cmd": "A=~10" },
  "0x77E1B047": { "label": "down", "cmnt": "Brightness -", "cmd": "A=~-10" },
  "0xD790F0D8": { "label": "down", "cmnt": "Brightness -", "cmd": {"bri":"~-30"} },
  "0xFEA6EDF3": { "label": "up", "cmnt": "Brightness +", "cmd": {"bri":"~+30"} },
  "0xC7C0EC40": { "label": "up", "cmnt": "Brightness +", "cmd": {"bri":"~+10"} },
  "0x77E11012": { "label": "left", "cmnt": "Effect -", "cmd": {"seg":{"fx":"~-"}} },
  "0x77E1E012": { "label": "right", "cmnt": "Effect +", "cmd": {"seg":{"fx":"~+"}} },
}
```
_My remote had multiple codes showing in the monitor for the same button._

Note the `{"bri":"~+30"}` - so the double tap increases/decreases the brightness by 30 instead of 10. A nice option for anyone who wants to use it, +/-50 could work even better as it will allow brightness to go from 0 to 255 much quicker.

Original code - I re-used `"cmd": "A=~8"` from the 18 key to see if there was any improvement: 
https://kno.wled.ge/interfaces/json-ir/18-key-ir.json
```
  "0x77E1D047": { "label": "up", "cmnt": "Brightness +", "cmd": {"bri":"~+10"} },
  "0x77E1B047": { "label": "down", "cmnt": "Brightness -", "cmd": {"bri":"~-10"} },
```

With those codes, holding the button (e.g. 2+ seconds) allowed the brightness to jump up the amount it would have gone if I had pressed the. button multiple times in that span of time. All you have to do is press it again once and it jumps after the hold. (Not sure if this works with other remotes.)


_N.B. After making this post, I made the SINGLE tap brightness go up/down 50 which worked well so just removed double tapping_

For future users, I've added my code here:
https://github.com/easaw/wled-apple-remote-json
