### ISSUE TITLE
ESP32-C3 SuperMini gets very hot

### ISSUE THREAD

**Issue by SunboX** [Aircoookie/WLED#4275]
### What happened?

ESP32-C3 get's very hot, you nearly can't touch it anymore after only 10 seconds.

### To Reproduce Bug

I flashed the latest WLED [env:esp32c3dev] from today onto a ESP32-C3 SuperMini from here: https://de.aliexpress.com/item/1005006960183178.html

No LEDs were connected at this time.

After doing a search, I came across other users with the same Issue. Flashing ESPHome does not heat it up so much. So it is not related to Wifi usage or the board in general. It must be somehow WLED related - but why?

### Expected Behavior

ESP32-C3 gets only warm not burning hot.

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.4 (build 2405180)

### Which microcontroller/board are you seeing the problem on?

ESP32-C3

### Anything else?

No, nothing was connected to the board, just USB power. The ESP32 chip itself got hot and also the voltage regulator.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
not a bug, that is just how it is.

**Comment by SunboX** [comment]
@DedeHai And why doesn't it happen if I install ESPHome?

**Comment by DedeHai** [comment]
Enable wifi sleep.

**Comment by SunboX** [comment]
It seems to help a tiny little bit, but still getting very hot.

**Comment by SunboX** [comment]
Even reducing f_cpu to 80MHz does no change.

**Comment by softhack007** [comment]
@SunboX there are small -C3 boards out there which have thermal problems. Maybe you were unlucky to get one.

Some known ways to reduce heat production:
* important: do not run audioreactive - it creates high CPU load on -C3
* uncheck "disable wifi sleep" (=allow wifi sleep) in WLED led settings
* reduce target fps in WLED LED settings
* custom build with reduced CPU frequency (80mhz instead of 160mhz)

You can't compare esphome with WLED. 
Esphome basicially reads out a handful of sensors and sends them over to MQTT or HA, maybe drives a handful of outputs at low rates. So in esphome the CPU is idle most of the time, while WLED is actively calculating effects and doing other things that keep the CPU busy = produce heat.

**Comment by SunboX** [comment]
@softhack007 Thanks for the explanation! That's really sad, the WEMOS D1 Mini (ESP8266) is also low CPU power but does not seem to have those issues. Do you know why?

**Comment by softhack007** [comment]
No idea, sorry. 8266 is a completely different CPU.

**Comment by softhack007** [comment]
Another idea that might help: 
Make a custom build with ` -DARDUINO_USB_CDC_ON_BOOT=0` instead of "=1" which is the default.

We had problems in the past with CDC_ON_BOOT enabled - the driver from espressif sometimes gets into an infinite loop at startup, which heats up the board. Unfortunately without CDC you can't set the wifi credentials in the online installer...

**Comment by softhack007** [comment]
Did I mention that -C3 is cheap useless stuff?  Well that's my personal opinion as a developer. If you can, buy -S3 (but not the superMini) or classic esp32.

**Comment by SunboX** [comment]
Yes, I know it's cheap, that's the reason why I want to use them. It's for small decorative stuff. I don't need an high end MyC for that. If it's cheap, it's fine. USB Type-C would be nice, because most chargers and cables nowadays have USB Type-C.

**Comment by DedeHai** [comment]
Reason your WEMOS D1 Mini does not suffer from this: it is roughtly 3x the size. I have C3 supermini's mounted on a just slightly larger carrier PCB and it does not get hot. The main issue is: it was designed to be mounted on a PCB, if not mounted, it will run hot. The temperature is not an issue for the hardware, it can easily take it.

**Comment by JZerf** [comment]
>     * don't run WLED in AP mode, always connect to a wifi router.

softhack007's suggestion of disabling AP mode and connecting to an existing wireless network helped significantly in my case. I was surprised that disabling AP mode would make such a large difference but it did. I also tried installing Tasmota on my ESP32-C3 to see if it also gets hot while running in AP mode (it operates in AP mode during the initial setup) and it also was running hot when using Tasmota as well. Seems like this problem with the ESP32-C3 running hot may be due to the ESP32-C3 hardware or some common underlying software.

**Comment by CWempe** [comment]
In case anybody was wondering what the difference is:

Disable WIFI Sleep: ✅

![Image](https://github.com/user-attachments/assets/c6b7c779-ef24-4a45-90d5-e6dee320a51d)

Disable WIFI Sleep: ❌

![Image](https://github.com/user-attachments/assets/689109f8-5ae2-45a2-9622-475d519b7eed)

So the temperature of the hotspot decreases from ~60 °C to 40 °C. 👍

I do not know yet what disadvantages this mode has.

**Comment by softhack007** [comment]
> I do not know yet what disadvantages this mode has.

Well "disable wifi sleep" off = "allow wifi (modem) sleep" has caused some problems in the past with realtime streaming, like AR sound sync, or DDP live leds.

However to benefit from reduced latency of "no sleep" mode, all the devices connected to you wifi AP (router) must agree on "no sleep" mode. Normally that's only possible if if you set up a dedicated router for your IOT WiFi network.
