### ISSUE TITLE
Transitions don't work with multiple segments (0.9.0-b1)

### ISSUE THREAD

**Issue by badbadc0ffee** [Aircoookie/WLED#465]
It looks like the transitions between effects don't work any longer when I use segements. When the while strip is used as one segment, the same transitions as seen with 0.8x versions work fine.

**Comment by Aircoookie** [comment]
Hi and thanks for reporting this issue!
Yes that is correct, transitions currently only work on brightness and the "main segment", which is Segment 0 by default. Supporting transitions for all segments would cost too much memory with the current implementation, but I already got something in mind to make it work soon :)

**Comment by bgberk** [comment]
Is there any update or insight into how this implementation might work? I'm looking to wire up a series of niches that can fade between colors or off and on independently and it seems like segments is the best way to do that (without needing a separate device controlling each niche).

**Comment by xBelladonna** [comment]
First of all, thank you very much for providing such a great project and absolutely stellar support to go with it! I'm also interested in overview/details of the implementation, since this limitation is currently the only thing preventing me from using segments as I value brightness transitions over segment control.

**Comment by blazoncek** [comment]
This is supposedly fixed in 0.13-b3. Closing.
Feel free to reopen if the issue persists.
