### ISSUE TITLE
values of returned XML file

### ISSUE THREAD

**Issue by f-zappa** [Aircoookie/WLED#56]
> "The basic URL scheme is: "[ipadress]/win". This will return an XML file with some current values."

The names of this values doesn't seem to match the "set" parameters and for most of them I couldn't figure out what they mean. Is there any documentation on the returned XML file?

**Comment by Aircoookie** [comment]
Ah yes, I'm sorry. This response is not self-explanatory at all since I built it to be as short as possible and therefore used 2-char identifiers. I added the meaning of each value to the API documentation.

Later in WLED 1.0.0 I will also offer an easier to read JSON API, but the current HTTP API will also remain accessible as a legacy or speed-focused option.

I hope you'll enjoy WLED!
