### ISSUE TITLE
Effect "Police All" works different with >100 LEDs

### ISSUE THREAD

**Issue by Def3nder** [Aircoookie/WLED#578]
With less then 100 Pixels the effect does fill the whole strip solid with RED / BLUE...
...but with more Pixels it's working different:

See this video: https://www.youtube.com/watch?v=wDoUTj43Q94

I tried to change the build flags from PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH (v2) to PIO_FRAMEWORK_ARDUINO_LWIP_HIGHER_BANDWIDTH (v1.4) but this did not have any effect.

I also tried to add segments: e.g, segment0 = 0...91, segment1 = 92...316 
After this the segment0 does display as expected (solid fill colors) but the 2nd segment stil has this strange behaviour.

Any suggestion how to change this ?

**Comment by Aircoookie** [comment]
Hi!
Thank you for making me aware of this! This problem happens when the effect speed and/or LED count is high enough to move the effect by more than one pixel every frame. That will lead to some of the pixels not getting filled (and then potentially getting filled with the second color, which effectively makes the effect purple). Will fix soon!

**Comment by Aircoookie** [comment]
also happens with Sinelon by the way, and Juggle (although the effect is quite nice with juggle ang i wouldn't neccessarily change that)

**Comment by Dreamoffice** [comment]
@Aircoookie 
i have another issue with Police All Effect. with 100 LED in the preferences it works like a charm but with more (i have 816) it works like on the video.
[https://youtu.be/ESaA0FjHbnU](url)

**Comment by Def3nder** [comment]
closed with PR #634
