### ISSUE TITLE
Allow for longer transition times

### ISSUE THREAD

**Issue by chaptergy** [Aircoookie/WLED#650]
Hey,

my specific problem is, I'm trying to create a light alarm using WLED leds using my home assistant. However in the wiki I read, that the max transition time is 65000ms, so about one minute. For this light alarm I'd want to set the transition to maybe 20 minutes. What was the reason for capping the transition time at this value?

Thanks!

**Comment by Aircoookie** [comment]
Hi,

yes, this is true because the transition time is stored in a 16-bit integer, so no transition times longer than about 65 secs are possible. I could change this in the future to reduce the precision to 100ms/step (which the JSON API currently uses), which would yield a transition range of up to 6500 seconds, so almost two hours.

That said, for now you might want to look into the Nightlight function :) You can set a duration and target brightness and it will essentially create a very slow brightness transition for you (1-255 minute range)

**Comment by Def3nder** [comment]
Hi @chaptergy, please try the "sun rise" feature of the NightLight for this.
Sun Rise is like Nightlight but with additional color-transition from the primary to the secondary color.
paste this string to one of the macro slots:

`&FX=0&CL=hFF7800&C2=hFFC28C&W2=255&A=5&NT=255&NL=20&NF=2`

It does the following:
- `&FX=0` ... set the Effect to "Solid Color"
- `&CL=hFF8C00`  ...  set the primary color to Redish
- `&C2=hFFC28C&W2=255`  ...  set the secondary color to a warm white (change this if you do not have a dedicated white color channel)
- `&A=5`  ...  set the starting brightness to 5 (about 2%)
- `&NT=255`  ...  set the target brightness to 255 (100%)
- `&NL=20`  ...  set the transition time to 20 minutes
`&NF=2`  ...  set Nightlight to "On with color transition"

Is this what you'd like to have ?

**Comment by chaptergy** [comment]
Hey,
thank you very much for your suggestions. However it seems this is unfortunately not possible through the home assistant integration.

**Comment by hansenchristian** [comment]
@chaptergy  I use home assistant too and I send my request over mqtt, works with @Def3nder 's solution perfectly
`service: mqtt.publish
data:
  topic: wled/test/api
  payload: '&FX=0&CL=hFF7800&C2=hFFC28C&W2=255&A=5&NT=255&NL=2&NF=2'`

**Comment by chaptergy** [comment]
> @chaptergy I use home assistant too and I send my request over mqtt, works with @Def3nder 's solution perfectly

Yes, his solution is a great workaround which works for me, too.

**Comment by daguej** [comment]
For anyone interested, I've posted a [patched version of WLED](https://github.com/daguej/WLED/releases) that supports transitions up to 24h.

With this patch running on your WLED device, changes triggered by Home Assistant with long transitions just work as expected.

**Comment by softhack007** [comment]
Please keep in mind that [the patch](https://github.com/wled/WLED/pull/5864) is very special-purpose. It was not accepted into the WLED core due to [side-effects](https://github.com/wled/WLED/issues/5375#issuecomment-3916499719) on other WLED features - especially WLED sync won't be able to synchronise transitions on several devices anymore, JSON API changes, potential presets incompatibilities, etc.

<br/> 

> For anyone interested, I've posted a patched version of WLED

The referenced binaries are neither reviewed nor tested by the WLED team. Only flash firmware from sources you trust. Prefer builds you compile yourself (from reviewed source code) over pre-compiled binaries distributed by strangers.
