### ISSUE TITLE
Groupings and Spacing not saved on Restart

### ISSUE THREAD

**Issue by ironosity** [Aircoookie/WLED#706]
Version:  0.9.1
Behavior: Set up spacing and grouping in Segment 0 is not being applied after restart.
Expected: If segment 0 is saved with spacing and grouping, it should be applied on restart.

Steps to reproducs:

1. change spacing and grouping values in segment 0.
2. save this. Note that it now works with all effects including saved presets.
3. Restart. Note that the effects/presets no longer respect groupings/spacing.

Work around:
After setting up segment 0 with groupings/spacings, save to preset 16 with desired effect.  Set preset 16 to come on after reboot.  Now on reboot, it will apply groupings/spacings to all effects

**Comment by Aircoookie** [comment]
Thank you!
This behavior is not really considered a bug, as I temporarily coded it this way to allow to stick to the old preset system until a better one is in place.
I do agree that this situation is not ideal, grouping allows for some really nice effects of which only a single one can be saved to preset 16. I will rework the preset saving data model soon so that you can have named presets and each of them can save segment parameters :)
