### ISSUE TITLE
New wifi sleep toggle overrules wifi_set_sleep_type in ArduinoOTA

### ISSUE THREAD

**Issue by feindsender** [Aircoookie/WLED#720]
Hi,
i just noticed that wifi_set_sleep_type(NONE_SLEEP_T) in wledInit() gets overwriten by
the new wifi sleep toggle feature.
I do not know if it is needed at all for ArduinoOTA or could be removed.

greetings
Maik

**Comment by Aircoookie** [comment]
Hi!
Thank you for the observation, but I am pretty sure it is correct the way it is.
The thing is with the new toggle you can set whether to use sleep mode in normal operation.
When an update is initiated, sleep has to be disabled at all times, because otherwise data could be missed and the update may fail.
Greetings :)
