### ISSUE TITLE
Suggestion for automatic brightness using LDR

### ISSUE THREAD

**Issue by olealm** [Aircoookie/WLED#857]
Light Dependant Resistor (LDR) is a simple, very cheap and stable solution I use in all rooms in my house for measuring light.
P.t. I'm adjusting WLED units brightness via MQTT from automations in Home Assistant, but would be great to have it done locally in the Wled controller. Because for example, during the day when the sun is up my WLED based analog wall clock obviously needs more brightness then at night.

Suggestion for a WLED option: Use an analog input (since even D1minis has one available AI), a LDR and a resistor to be able to automatically adjust LED brightness.

**Comment by nordeep** [comment]
I have a few Witty ESP8266 with integrated LDR. It would be great to have this feature!

**Comment by cyber-junkie9** [comment]
is there any update on this ?

**Comment by shupershuff** [comment]
+1

**Comment by blazoncek** [comment]
There is a usermod for LDR (SN_Photoresistor). Check with author if it can fulfil your request or be modified for it..

**Comment by blazoncek** [comment]
No feedback received, closing.

**Comment by YvesLev** [comment]
Hello,

Since WLED support of Led Matrix panel and scrolling text, I have built two wall clock that also shows outdoor temperature (I use API to send the temperature from Sensor in Home Assistant), I find that it would be really pratical to have an auto brightness adjustment.
LDR probably could do the job.

It would be great if it could be integrated in the stock fw with the use of Analog Input that is already available.
But we are missing the possibility to adjust the range.

For example, I would like to be able to configure the Minumum brightness et maximum brightness that the analog input can control AND also the analog values that correspond to the min and max brightness.
Any analog values outside the min / max would have no effects (Clamping).

For exemple:
<=0.8V = 10% (25) Brightness
>=3.0V = 100% (255) Brightness

That is if we assume there is a linear correspondance...

So I believe that having at least a Usermod that do the Auto brightness adjustement with a LDR or BH1750 would be great (it should also offer some configuration parameters...)

Thank you.

Yves

**Comment by blazoncek** [comment]
@YvesLev there are two photo resistors usermods present, unfortunately both unmaintained. Please contact their authors for further development.
LDR will not be implemented in core.

**Comment by JeffWDH** [comment]
Is there a reason for this stance of not implementing in core? It is a very useful functionality for people who only want lighting when it is dark.

**Comment by blazoncek** [comment]
> Is there a reason for this stance of not implementing in core? It is a very useful functionality for people who only want lighting when it is dark.

Nobody is prohibiting you (or anybody else) from implementing it.

**Comment by JeffWDH** [comment]
I interpreted your response as LDR support was a forbidden feature, not that somebody would need to contribute it... Thanks for confirming!

**Comment by blazoncek** [comment]
I still think that LDR does not belong into WLED core as very few people use such functionality.
As a usermod, it is completely different picture.

**Comment by JeffWDH** [comment]
I would argue it's just as useful as an IR remote, but I think the lowest barrier for entry will be to add it as a usermod.

**Comment by blazoncek** [comment]
> I would argue it's just as useful as an IR remote, but I think the lowest barrier for entry will be to add it as a usermod.

Well? What are you waiting for, then? 😉 Joke aside, perhaps best to contact original usermod authors if they can be persuaded to invest some additional time to update existing usermods.

As for IR, I know of a certain hardware, sold in thousands, that has IR capabilities used daily by thousands of users. I have yet to discover hardware with integrated LDR.

**Comment by moeburn** [comment]
+1 I would also use it.  A TEPT4400 but serves the same purpose.  Would like some way of automatically adjusting brightness other than time macros because I use WLED indoors where time is of no consequence.
