### ISSUE TITLE
More MQTT Functionality please

### ISSUE THREAD

**Issue by Beliar-666** [Aircoookie/WLED#96]
Maybe there has to be an upgrade for the MQTT section. I Think changing Speed and Palette and so aon should also be changeable via MQTT. So i can integrate it in my Smarthomeprojekt via IoBroker easily.

**Comment by Aircoookie** [comment]
Hi, you can set the speed and any other value via MQTT using the http API syntax by publishing to the *wled/[devicename]/api* topic. To set speed, use "SX=[speed]. I know this is not as convenient as having separate topics for speed, intensity, palette and other values, but I believe subscribing to so many topics would impact the performance too much.

**Comment by DutchmanNL** [comment]
Hi, is there documentation available related to the http API ?
i am a member of the ioBroker team and created already some adapters for it. Your project is great and works very well !
I just finished my first setup with this GitHub project on 3 WS2812b stripes some just directly controlled and other integrated with Hyperion. 
I must say much credits for the people behind it, the adoption is very easy and like the broad compatibility with controllers!

So for me (and all people using it) I would be very interested in creating an 1:1 adapter solution to enable user to directly integrate WLED with just some simple clicks in this iOT solution.


To make this possible I would like to understand the communication possibilities by API/MQTT (HTTP api would be most interesting).

 https://github.com/ioBroker/AdapterRequests/issues/165

**Comment by Aircoookie** [comment]
Hi @DutchmanNL !
Awesome that you like WLED! I'm really honored that you consider writing an adapter for ioBroker!
You can find the HTTP API documentation here: https://github.com/Aircoookie/WLED/wiki/HTTP-request-API

You can send a GET, POST or PUT request, WLED doesn't distinguish between them. Also you can just GET `http://[device-ip]/win` to get the current device state as XML. If you prefer JSON, I think I could add that as well, but it's not supported currently.

Let me know if there is anything I can help you with while creating the adapter :) 
Thank you!

**Comment by DutchmanNL** [comment]
Hi,

Thank you providing feedback!
Yea cool source like WLED needs a cool iOT system like iObroker and a cool iOT system needs cool stuff like WLED :-)

So let's get started with it maybe I should open a separate issue for that ?

I need to investigate the most efficient communication and MQTT is not the best way to go.
So I will take the basic on http or broadcast.

As jou mention for an initial pull of all data I would prefer a JSON so if that could be added integration would be a little easier.
By that I can make a single call based on JSON an create the structure.

Will have a look a little more in detail to the code as broadcast is also an interesting starting point.

You are aware of the JSON library's to build an send that kind of data (otherwise I could bring you in contact with someone knowing it very well)

**Comment by Aircoookie** [comment]
Yes, I agree we should discuss this in a separate issue, since it has little to do with this MQTT issue, so I opened #102!

**Comment by Aircoookie** [comment]
MQTT rework is discussed in #207  :)
